// ==========================================
// 1. DATA SOALAN PERMAINAN (GAME DATA)
// ==========================================
const gameData = {
missing: [
        { "q": "E N I G M _ T I C (Difficult to understand or interpret)", "a": "a" },
        { "q": "P E R S E V _ R A N C E (Persistence in doing something)", "a": "e" },
        { "q": "A B _ N D A N T (Existing or available in large quantities)", "a": "u" },
        { "q": "M E T I C U L O _ S (Showing great attention to detail)", "a": "u" },
        { "q": "E Q U I L _ B R I U M (A state of balance)", "a": "i" },
        { "q": "P H I L A N T _ R O P Y (The desire to promote the welfare of others)", "a": "h" },
        { "q": "C O M P R _ H E N S I V E (Complete and including everything necessary)", "a": "e" },
        { "q": "E _ A C E R B A T E (Make a problem or bad situation worse)", "a": "x" },
        { "q": "A _ T H E N T I C (Of undisputed origin; genuine)", "a": "u" },
        { "q": "E P H E M _ R A L (Lasting for a very short time)", "a": "e" },
        { "q": "M E L _ N C H O L Y (A feeling of pensive sadness)", "a": "a" },
        { "q": "O B F U S _ A T E (Render obscure, unclear, or unintelligible)", "a": "c" },
        { "q": "P A R _ D I G M (A typical example or pattern of something)", "a": "a" },
        { "q": "C A C _ P H O N Y (A harsh, discordant mixture of sounds)", "a": "o" },
        { "q": "T R _ P I D A T I O N (A feeling of fear or agitation about the future)", "a": "e" },
        { "q": "A M B _ G U O U S (Open to more than one interpretation)", "a": "i" },
        { "q": "R E S _ L I E N T (Able to withstand or recover quickly from difficult conditions)", "a": "i" },
        { "q": "V O C _ F E R O U S (Vehement or clamorous in speech)", "a": "i" },
        { "q": "E U P H _ R I A (A feeling or state of intense excitement and happiness)", "a": "o" },
        { "q": "S Y C O P _ A N T (A person who acts obsequiously toward someone important)", "a": "h" },
        { "q": "P R A G M _ T I C (Dealing with things sensibly and realistically)", "a": "a" },
        { "q": "U B I Q U _ T O U S (Present, appearing, or found everywhere)", "a": "i" },
        { "q": "N _ S T A L G I A (A sentimental longing for the past)", "a": "o" },
        { "q": "F A C _ T I O U S (Treating serious issues with inappropriate humor)", "a": "e" },
        { "q": "S E R E N D I P I T _ (The occurrence of events by chance in a happy way)", "a": "y" },
        { "q": "E L O Q U _ N T (Fluent or persuasive in speaking or writing)", "a": "e" },
        { "q": "C O N _ N D R U M (A confusing and difficult problem or question)", "a": "u" },
        { "q": "I N E V I T _ B L E (Certain to happen; unavoidable)", "a": "a" },
        { "q": "C H A R I S M _ T I C (Exercising a compelling charm that inspires devotion)", "a": "a" },
        { "q": "M A G N A N _ M O U S (Very generous or forgiving)", "a": "i" },
        { "q": "A C Q U I _ S C E (Accept something reluctantly but without protest)", "a": "e" },
        { "q": "O B S _ L E T E (No longer produced or used; out of date)", "a": "o" },
        { "q": "P R O L _ F I C (Present in large numbers or quantities; plentiful)", "a": "i" },
        { "q": "S P O N T _ N E O U S (Occurring as a result of a sudden inner impulse)", "a": "a" },
        { "q": "T E N _ C I O U S (Tending to keep a firm hold of something)", "a": "a" },
        { "q": "L U C R _ T I V E (Producing a great deal of profit)", "a": "a" },
        { "q": "P A N _ C E A (A solution or remedy for all difficulties or diseases)", "a": "a" },
        { "q": "S U R R _ P T I T I O U S (Kept secret, especially because it would not be approved of)", "a": "e" },
        { "q": "V I N D _ C A T E (Clear someone of blame or suspicion)", "a": "i" },
        { "q": "J U X T A P _ S I T I O N (The fact of two things being seen or placed close together)", "a": "o" },
        { "q": "I N _ I D I O U S (Proceeding in a gradual, subtle way, but with harmful effects)", "a": "s" },
        { "q": "P L _ T H O R A (A large or excessive amount of something)", "a": "e" },
        { "q": "C _ R R O B O R A T E (Confirm or give support to a statement or theory)", "a": "o" },
        { "q": "E X _ N E R A T E (Absolve someone from blame for a fault or wrongdoing)", "a": "o" },
        { "q": "G R E G _ R I O U S (Fond of company; sociable)", "a": "a" },
        { "q": "I D I O S Y N C R _ S Y (A mode of behavior peculiar to an individual)", "a": "a" },
        { "q": "M A L _ V O L E N T (Having or showing a wish to do evil to others)", "a": "e" },
        { "q": "N E F _ R I O U S (Wicked or criminal)", "a": "a" },
        { "q": "R E C A L C I T R _ N T (Having an obstinately uncooperative attitude)", "a": "a" },
        { "q": "A N O M _ L Y (Something that deviates from what is standard or expected)", "a": "a" }
],
    
   pastTense: [
        { "q": "What is the past tense of ARISE?", "a": "arose" },
        { "q": "What is the past tense of AWAKE?", "a": "awoke" },
        { "q": "What is the past tense of BEAR?", "a": "bore" },
        { "q": "What is the past tense of BEFALL?", "a": "befell" },
        { "q": "What is the past tense of BESEECH?", "a": "besought" },
        { "q": "What is the past tense of BIND?", "a": "bound" },
        { "q": "What is the past tense of BLEED?", "a": "bled" },
        { "q": "What is the past tense of BREED?", "a": "bred" },
        { "q": "What is the past tense of BROADCAST?", "a": "broadcast" },
        { "q": "What is the past tense of CAST?", "a": "cast" },
        { "q": "What is the past tense of CLING?", "a": "clung" },
        { "q": "What is the past tense of CREEP?", "a": "crept" },
        { "q": "What is the past tense of DEAL?", "a": "dealt" },
        { "q": "What is the past tense of DIG?", "a": "dug" },
        { "q": "What is the past tense of DWELL?", "a": "dwelt" },
        { "q": "What is the past tense of FLEE?", "a": "fled" },
        { "q": "What is the past tense of FLING?", "a": "flung" },
        { "q": "What is the past tense of FORBID?", "a": "forbade" },
        { "q": "What is the past tense of FORESEE?", "a": "foresaw" },
        { "q": "What is the past tense of FORGIVE?", "a": "forgave" },
        { "q": "What is the past tense of FORSAKE?", "a": "forsook" },
        { "q": "What is the past tense of FREEZE?", "a": "froze" },
        { "q": "What is the past tense of GRIND?", "a": "ground" },
        { "q": "What is the past tense of HANG?", "a": "hung" },
        { "q": "What is the past tense of KNEEL?", "a": "knelt" },
        { "q": "What is the past tense of LAY?", "a": "laid" },
        { "q": "What is the past tense of LIE?", "a": "lay" },
        { "q": "What is the past tense of LIGHT?", "a": "lit" },
        { "q": "What is the past tense of OVERTAKE?", "a": "overtook" },
        { "q": "What is the past tense of QUIT?", "a": "quit" },
        { "q": "What is the past tense of SEEK?", "a": "sought" },
        { "q": "What is the past tense of SHED?", "a": "shed" },
        { "q": "What is the past tense of SHINE?", "a": "shone" },
        { "q": "What is the past tense of SHRINK?", "a": "shrank" },
        { "q": "What is the past tense of SINK?", "a": "sank" },
        { "q": "What is the past tense of SLAY?", "a": "slew" },
        { "q": "What is the past tense of SLIDE?", "a": "slid" },
        { "q": "What is the past tense of SLIT?", "a": "slit" },
        { "q": "What is the past tense of SMITE?", "a": "smote" },
        { "q": "What is the past tense of SPIN?", "a": "spun" },
        { "q": "What is the past tense of SPIT?", "a": "spat" },
        { "q": "What is the past tense of SPRING?", "a": "sprang" },
        { "q": "What is the past tense of STINK?", "a": "stank" },
        { "q": "What is the past tense of STRIDE?", "a": "strode" },
        { "q": "What is the past tense of STRIVE?", "a": "strove" },
        { "q": "What is the past tense of THRUST?", "a": "thrust" },
        { "q": "What is the past tense of TREAD?", "a": "trod" },
        { "q": "What is the past tense of WEAVE?", "a": "wove" },
        { "q": "What is the past tense of WEEP?", "a": "wept" },
        { "q": "What is the past tense of WRING?", "a": "wrung" }
    ],
    
plural: [
        { "q": "One criterion, many ...?", "a": "criteria" },
        { "q": "One phenomenon, several ...?", "a": "phenomena" },
        { "q": "One alumnus, many ...?", "a": "alumni" },
        { "q": "One alumna, two ...?", "a": "alumnae" },
        { "q": "One syllabus, many ...?", "a": "syllabi" },
        { "q": "One cactus, several ...?", "a": "cacti" },
        { "q": "One fungus, many ...?", "a": "fungi" },
        { "q": "One nucleus, two ...?", "a": "nuclei" },
        { "q": "One focus, multiple ...?", "a": "foci" },
        { "q": "One radius, two ...?", "a": "radii" },
        { "q": "One stimulus, many ...?", "a": "stimuli" },
        { "q": "One thesis, several ...?", "a": "theses" },
        { "q": "One crisis, many ...?", "a": "crises" },
        { "q": "One hypothesis, two ...?", "a": "hypotheses" },
        { "q": "One oasis, several ...?", "a": "oases" },
        { "q": "One diagnosis, multiple ...?", "a": "diagnoses" },
        { "q": "One analysis, two ...?", "a": "analyses" },
        { "q": "One basis, many ...?", "a": "bases" },
        { "q": "One neurosis, several ...?", "a": "neuroses" },
        { "q": "One appendix, two ...?", "a": "appendices" },
        { "q": "One index, multiple ...?", "a": "indices" },
        { "q": "One matrix, two ...?", "a": "matrices" },
        { "q": "One vertex, many ...?", "a": "vertices" },
        { "q": "One apex, two ...?", "a": "apices" },
        { "q": "One datum, much ...?", "a": "data" },
        { "q": "One medium, many ...?", "a": "media" },
        { "q": "One stratum, several ...?", "a": "strata" },
        { "q": "One curriculum, many ...?", "a": "curricula" },
        { "q": "One bacterium, millions of ...?", "a": "bacteria" },
        { "q": "One millennium, several ...?", "a": "millennia" },
        { "q": "One symposium, two ...?", "a": "symposia" },
        { "q": "One antenna, two ...?", "a": "antennae" },
        { "q": "One formula, many ...?", "a": "formulae" },
        { "q": "One vertebra, several ...?", "a": "vertebrae" },
        { "q": "One larva, hundreds of ...?", "a": "larvae" },
        { "q": "One moose, a herd of ...?", "a": "moose" },
        { "q": "One aircraft, a fleet of ...?", "a": "aircraft" },
        { "q": "One offspring, many ...?", "a": "offspring" },
        { "q": "One species, thousands of ...?", "a": "species" },
        { "q": "One series, multiple ...?", "a": "series" },
        { "q": "One salmon, a school of ...?", "a": "salmon" },
        { "q": "One bison, a herd of ...?", "a": "bison" },
        { "q": "One louse, a head full of ...?", "a": "lice" },
        { "q": "One die, a pair of ...?", "a": "dice" },
        { "q": "One beau, two ...?", "a": "beaux" },
        { "q": "One chateau, several ...?", "a": "chateaux" },
        { "q": "One tableau, many ...?", "a": "tableaux" },
        { "q": "One oxymoron, several ...?", "a": "oxymora" },
        { "q": "One automaton, multiple ...?", "a": "automata" },
        { "q": "One polyhedron, several ...?", "a": "polyhedra" }
    ],
    
    spelling: [
        { q: "Fix the spelling: BEUTIFUL", a: "beautiful" },
        { q: "Fix the spelling: TOMOROW", a: "tomorrow" },
        { q: "Fix the spelling: WENSDAY", a: "wednesday" },
        { q: "Fix the spelling: RECIEVE", a: "receive" },
        { q: "Fix the spelling: ACOMDATE", a: "accommodate" },
        { q: "Fix the spelling: DEFINATELY", a: "definitely" },
        { q: "Fix the spelling: SEPERATE", a: "separate" },
        { q: "Fix the spelling: UNTILL", a: "until" },
        { q: "Fix the spelling: OCCURED", a: "occurred" },
        { q: "Fix the spelling: ALOT (one word)", a: "a lot" },
        { q: "Fix the spelling: ARGUMANT", a: "argument" },
        { q: "Fix the spelling: CALENDER", a: "calendar" },
        { q: "Fix the spelling: COLUM", a: "column" },
        { q: "Fix the spelling: EMBARASS", a: "embarrass" },
        { q: "Fix the spelling: EXISTANCE", a: "existence" },
        { q: "Fix the spelling: FORIEGN", a: "foreign" },
        { q: "Fix the spelling: FOURTY", a: "forty" },
        { q: "Fix the spelling: GOVERMENT", a: "government" },
        { q: "Fix the spelling: INDEPENDANT", a: "independent" },
        { q: "Fix the spelling: INTERUPT", a: "interrupt" },
        { q: "Fix the spelling: JELOUS", a: "jealous" },
        { q: "Fix the spelling: KNOWLEDG", a: "knowledge" },
        { q: "Fix the spelling: MISTERY", a: "mystery" },
        { q: "Fix the spelling: NECESARY", a: "necessary" },
        { q: "Fix the spelling: NOTICABLE", a: "noticeable" },
        { q: "Fix the spelling: OCASION", a: "occasion" },
        { q: "Fix the spelling: PEICE", a: "piece" },
        { q: "Fix the spelling: POSESSION", a: "possession" },
        { q: "Fix the spelling: PRIVILEDGE", a: "privilege" },
        { q: "Fix the spelling: PRONOUNCIATION", a: "pronunciation" },
        { q: "Fix the spelling: REALY", a: "really" },
        { q: "Fix the spelling: RECCOMEND", a: "recommend" },
        { q: "Fix the spelling: RYTHM", a: "rhythm" },
        { q: "Fix the spelling: SENSEBLE", a: "sensible" },
        { q: "Fix the spelling: SUCCESFUL", a: "successful" },
        { q: "Fix the spelling: SUPRISE", a: "surprise" },
        { q: "Fix the spelling: TENDANCY", a: "tendency" },
        { q: "Fix the spelling: THREFORE", a: "therefore" },
        { q: "Fix the spelling: TONG", a: "tongue" },
        { q: "Fix the spelling: TRULEY", a: "truly" },
        { q: "Fix the spelling: UNFORGETABLE", a: "unforgettable" },
        { q: "Fix the spelling: WEAKEND (Saturday & Sunday)", a: "weekend" },
        { q: "Fix the spelling: WIERD", a: "weird" },
        { q: "Fix the spelling: WRITTING", a: "writing" },
        { q: "Fix the spelling: ACHIVE", a: "achieve" },
        { q: "Fix the spelling: ADDRES", a: "address" },
        { q: "Fix the spelling: BIZNESS", a: "business" },
        { q: "Fix the spelling: ENVIROMENT", a: "environment" },
        { q: "Fix the spelling: FAMILIER", a: "familiar" },
        { q: "Fix the spelling: MINIT", a: "minute" }
    ],
        
guessing: [
        { "q": "I speak without a mouth and hear without ears. I have no body, but I come alive with wind.", "a": "echo" },
        { "q": "I am not alive, but I grow; I don't have lungs, but I need air; I don't have a mouth, but water kills me.", "a": "fire" },
        { "q": "I have cities, but no houses. I have mountains, but no trees. I have water, but no fish.", "a": "map" },
        { "q": "I fly without wings. I cry without eyes. Whenever I go, darkness flies.", "a": "cloud" },
        { "q": "I am a word of letters three, add two and fewer there will be.", "a": "few" },
        { "q": "I am a gas that makes up about 78% of the Earth's atmosphere.", "a": "nitrogen" },
        { "q": "I am the lightest and most abundant element in the universe.", "a": "hydrogen" },
        { "q": "I am the subatomic particle with a negative electrical charge.", "a": "electron" },
        { "q": "I am the theoretical boundary around a black hole beyond which nothing can escape.", "a": "event horizon" },
        { "q": "I am the biological process by which plants convert light energy into chemical energy.", "a": "photosynthesis" },
        { "q": "I am the longest and strongest bone in the human body.", "a": "femur" },
        { "q": "I am the hardest naturally occurring substance found on Earth.", "a": "diamond" },
        { "q": "I am the ancient writing system used in Egypt, utilizing pictures and symbols.", "a": "hieroglyphics" },
        { "q": "I am the fundamental force that causes mutual attraction between all things with mass.", "a": "gravity" },
        { "q": "I am the strait that separates Asia from North America.", "a": "bering" },
        { "q": "I am the deepest known part of the world's oceans.", "a": "mariana trench" },
        { "q": "I am the extreme or irrational fear of confined places.", "a": "claustrophobia" },
        { "q": "I am a geometric polygon with exactly twelve sides.", "a": "dodecagon" },
        { "q": "I am the organ in the human body responsible for producing insulin.", "a": "pancreas" },
        { "q": "I am the lowest layer of Earth's atmosphere, where most weather occurs.", "a": "troposphere" },
        { "q": "I am the phenomenon where light is bent as it passes from one medium to another.", "a": "refraction" },
        { "q": "I am the term for a word, phrase, or sequence that reads the same backwards as forwards.", "a": "palindrome" },
        { "q": "I am the protein that carries oxygen in the red blood cells of vertebrates.", "a": "hemoglobin" },
        { "q": "I am the proposed geological epoch dating from the commencement of significant human impact on Earth.", "a": "anthropocene" },
        { "q": "I am the branch of mathematics dealing with rates of change and accumulation.", "a": "calculus" },
        { "q": "I am a state of matter consisting of highly ionized gas.", "a": "plasma" },
        { "q": "I am the scientist who formulated the theory of general relativity.", "a": "einstein" },
        { "q": "I am the descriptive term for an animal that is active primarily during the night.", "a": "nocturnal" },
        { "q": "I am the specialized cell transmitting nerve impulses; a nerve cell.", "a": "neuron" },
        { "q": "I am the rigid outer part of the earth, consisting of the crust and upper mantle.", "a": "lithosphere" },
        { "q": "I am the massive supercontinent that existed during the late Paleozoic and early Mesozoic eras.", "a": "pangaea" },
        { "q": "I am the ancient Greek author traditionally credited with the epic poems The Iliad and The Odyssey.", "a": "homer" },
        { "q": "I am the microscopic structural and functional unit of the kidney.", "a": "nephron" },
        { "q": "I am the chemical breakdown of a substance by bacteria, yeasts, or other microorganisms.", "a": "fermentation" },
        { "q": "I am the natural light display in the Earth's sky, predominantly seen in high-latitude regions.", "a": "aurora" },
        { "q": "I am the derived unit of electrical resistance in the International System of Units.", "a": "ohm" },
        { "q": "I am a machine that converts mechanical energy into electrical energy.", "a": "generator" },
        { "q": "I am the first noble gas on the periodic table to have an atomic number in the double digits.", "a": "neon" },
        { "q": "I am the largest solid internal organ in the human body.", "a": "liver" },
        { "q": "I am the powerful and luminous stellar explosion that occurs at the end of a massive star's life cycle.", "a": "supernova" },
        { "q": "I am a stringed instrument played with a bow, larger than a viola but smaller than a double bass.", "a": "cello" },
        { "q": "I am the biological term for a symbiotic relationship where both interacting species benefit.", "a": "mutualism" },
        { "q": "I am the component of the human eye that changes shape to focus light on the retina.", "a": "lens" },
        { "q": "I am the mythological bird that regenerates or is reborn from its own ashes.", "a": "phoenix" },
        { "q": "I am the capital city of Australia, situated inland between Sydney and Melbourne.", "a": "canberra" },
        { "q": "I am the mathematical constant representing the ratio of a circle's circumference to its diameter.", "a": "pi" },
        { "q": "I am the type of rock formed through the cooling and solidification of magma or lava.", "a": "igneous" },
        { "q": "I am the positively charged subatomic particle found in the nucleus of an atom.", "a": "proton" },
        { "q": "I am the green pigment responsible for the absorption of light to provide energy for photosynthesis.", "a": "chlorophyll" },
        { "q": "I am the force that opposes the relative motion or tendency of such motion of two surfaces in contact.", "a": "friction" }
    ],
        
    puzzle: [
        { q: "C-H-E-A-T-R-E", a: "teacher" }, { q: "D-N-I-E-F-R", a: "friend" },
        { q: "N-D-A-G-R-E", a: "garden" }, { q: "D-O-W-W-I-N", a: "window" },
        { q: "L-Y-M-A-I-F", a: "family" }, { q: "G-N-E-R-O-A", a: "orange" },
        { q: "R-E-T-M-O-H", a: "mother" }, { q: "R-A-H-T-F-E", a: "father" },
        { q: "T-I-C-S-P-A-L", a: "plastic" }, { q: "T-E-L-T-O-B", a: "bottle" },
        { q: "K-E-R-M-A-T", a: "market" }, { q: "L-I-C-E-N-P", a: "pencil" },
        { q: "R-U-M-S-M-E", a: "summer" }, { q: "T-E-N-I-R-W", a: "winter" },
        { q: "F-E-E-O-C-F", a: "coffee" }, { q: "R-E-N-N-I-D", a: "dinner" },
        { q: "W-O-L-E-Y-L", a: "yellow" }, { q: "E-D-G-R-I-B", a: "bridge" },
        { q: "K-E-N-I-C-C-H", a: "chicken" }, { q: "N-I-P-L-O-H-D", a: "dolphin" },
        { q: "R-G-E-U-M-A-H-R-B", a: "hamburger" }, { q: "N-I-A-T-O-U-M-N", a: "mountain" },
        { q: "L-A-T-P-I-O-S-H", a: "hospital" }, { q: "Y-A-D-H-T-R-I-B", a: "birthday" },
        { q: "T-N-A-H-E-P-E-L", a: "elephant" }, { q: "R-E-T-U-P-O-M-C", a: "computer" },
        { q: "N-E-H-C-T-I-K", a: "kitchen" }, { q: "H-C-I-W-D-N-A-S", a: "sandwich" },
        { q: "E-L-B-A-T-E-G-E-V", a: "vegetable" }, { q: "E-S-R-E-V-I-N-U", a: "universe" },
        { q: "Y-R-A-R-B-I-L", a: "library" }, { q: "N-I-A-T-P-A-C", a: "captain" },
        { q: "Y-A-D-I-L-O-H", a: "holiday" }, { q: "Y-L-F-R-E-T-T-U-B", a: "butterfly" },
        { q: "D-N-O-M-A-I-D", a: "diamond" }, { q: "L-A-V-I-T-S-E-F", a: "festival" },
        { q: "E-N-I-Z-A-G-A-M", a: "magazine" }, { q: "R-U-O-B-H-G-I-E-N", a: "neighbour" },
        { q: "N-O-I-T-S-E-U-Q", a: "question" }, { q: "Y-R-R-E-B-W-A-R-T-S", a: "strawberry" },
        { q: "E-L-G-N-A-I-R-T", a: "triangle" }, { q: "E-G-A-L-L-I-V", a: "village" },
        { q: "R-E-H-T-A-E-W", a: "weather" }, { q: "Y-A-D-R-E-T-S-E-Y", a: "yesterday" },
        { q: "A-R-B-E-Z", a: "zebra" }, { q: "L-A-M-I-N-A", a: "animal" },
        { q: "L-U-F-I-T-U-A-E-B", a: "beautiful" }, { q: "Y-R-T-N-U-O-C", a: "country" },
        { q: "S-U-O-R-E-G-N-A-D", a: "dangerous" }, { q: "E-S-I-C-R-E-X-E", a: "exercise" }
    ],
        
    synonym: [
        { q: "Synonym of 'Happy'", a: "joyful|glad|cheerful" },
        { q: "Synonym of 'Big'", a: "huge|large|giant" },
        { q: "Synonym of 'Fast'", a: "quick|rapid|speedy" },
        { q: "Synonym of 'Smart'", a: "intelligent|clever|bright" },
        { q: "Synonym of 'Small'", a: "tiny|little|mini" },
        { q: "Synonym of 'Beautiful'", a: "pretty|lovely|gorgeous" },
        { q: "Synonym of 'Quiet'", a: "silent|calm|peaceful" },
        { q: "Synonym of 'Simple'", a: "easy|basic|plain" },
        { q: "Synonym of 'Sick'", a: "ill|unwell" },
        { q: "Synonym of 'Angry'", a: "mad|furious" },
        { q: "Synonym of 'Gift'", a: "present|reward" },
        { q: "Synonym of 'Begin'", a: "start|commence" },
        { q: "Synonym of 'Sad'", a: "unhappy|sorrowful|depressed" },
        { q: "Synonym of 'Funny'", a: "hilarious|comical|amusing" },
        { q: "Synonym of 'Shout'", a: "yell|scream|cry" },
        { q: "Synonym of 'Scared'", a: "afraid|frightened|terrified" },
        { q: "Synonym of 'Rich'", a: "wealthy|affluent" },
        { q: "Synonym of 'Buy'", a: "purchase|get" },
        { q: "Synonym of 'Finish'", a: "end|complete|conclude" },
        { q: "Synonym of 'Help'", a: "assist|support|aid" },
        { q: "Synonym of 'Idea'", a: "thought|concept|plan" },
        { q: "Synonym of 'Job'", a: "work|occupation|career" },
        { q: "Synonym of 'Look'", a: "see|watch|stare" },
        { q: "Synonym of 'Make'", a: "create|build|produce" },
        { q: "Synonym of 'Neat'", a: "tidy|clean|orderly" },
        { q: "Synonym of 'Old'", a: "ancient|aged" },
        { q: "Synonym of 'Part'", a: "section|piece|portion" },
        { q: "Synonym of 'Right'", a: "correct|accurate|true" },
        { q: "Synonym of 'Safe'", a: "secure|protected" },
        { q: "Synonym of 'Tell'", a: "say|speak|inform" },
        { q: "Synonym of 'Use'", a: "utilize|employ" },
        { q: "Synonym of 'Wrong'", a: "incorrect|false|mistaken" },
        { q: "Synonym of 'Always'", a: "forever|constantly" },
        { q: "Synonym of 'Brave'", a: "courageous|fearless|bold" },
        { q: "Synonym of 'Cold'", a: "chilly|freezing|cool" },
        { q: "Synonym of 'Dirty'", a: "messy|unclean|filthy" },
        { q: "Synonym of 'Enjoy'", a: "like|love|appreciate" },
        { q: "Synonym of 'Famous'", a: "well-known|popular|renowned" },
        { q: "Synonym of 'Good'", a: "great|excellent|fine" },
        { q: "Synonym of 'Hard'", a: "difficult|tough|solid" },
        { q: "Synonym of 'Important'", a: "crucial|significant|vital" },
        { q: "Synonym of 'Jump'", a: "leap|hop|bounce" },
        { q: "Synonym of 'Keep'", a: "hold|save|retain" },
        { q: "Synonym of 'Lazy'", a: "idle|sluggish|inactive" },
        { q: "Synonym of 'Many'", a: "numerous|multiple|plenty" },
        { q: "Synonym of 'New'", a: "fresh|modern|recent" },
        { q: "Synonym of 'Polite'", a: "courteous|respectful|civil" },
        { q: "Synonym of 'Strong'", a: "powerful|tough|sturdy" },
        { q: "Synonym of 'Tired'", a: "sleepy|exhausted|fatigued" },
        { q: "Synonym of 'Weak'", a: "frail|fragile|feeble" }
    ],
        
    antonym: [
        { q: "Antonym of 'Hot'", a: "cold|freezing" },
        { q: "Antonym of 'Up'", a: "down" },
        { q: "Antonym of 'Good'", a: "bad|evil|terrible" },
        { q: "Antonym of 'Fast'", a: "slow" },
        { q: "Antonym of 'Happy'", a: "sad|unhappy|depressed" },
        { q: "Antonym of 'Big'", a: "small|tiny|little" },
        { q: "Antonym of 'Light'", a: "dark|heavy" },
        { q: "Antonym of 'Day'", a: "night" },
        { q: "Antonym of 'Open'", a: "close|closed|shut" },
        { q: "Antonym of 'New'", a: "old|ancient" },
        { q: "Antonym of 'Rich'", a: "poor|broke" },
        { q: "Antonym of 'Hard'", a: "soft|easy" },
        { q: "Antonym of 'Empty'", a: "full" },
        { q: "Antonym of 'Clean'", a: "dirty|messy" },
        { q: "Antonym of 'Strong'", a: "weak|frail" },
        { q: "Antonym of 'Right'", a: "wrong|left" },
        { q: "Antonym of 'Tall'", a: "short" },
        { q: "Antonym of 'Beautiful'", a: "ugly" },
        { q: "Antonym of 'Brave'", a: "coward|scared|fearful" },
        { q: "Antonym of 'Cheap'", a: "expensive|costly" },
        { q: "Antonym of 'Cry'", a: "laugh|smile" },
        { q: "Antonym of 'Early'", a: "late" },
        { q: "Antonym of 'Fat'", a: "thin|skinny|slim" },
        { q: "Antonym of 'First'", a: "last|final" },
        { q: "Antonym of 'Friend'", a: "enemy|foe" },
        { q: "Antonym of 'Give'", a: "take|receive" },
        { q: "Antonym of 'Inside'", a: "outside" },
        { q: "Antonym of 'Loud'", a: "quiet|silent|soft" },
        { q: "Antonym of 'Love'", a: "hate|dislike" },
        { q: "Antonym of 'Near'", a: "far|distant" },
        { q: "Antonym of 'Never'", a: "always|forever" },
        { q: "Antonym of 'Pull'", a: "push" },
        { q: "Antonym of 'Rough'", a: "smooth|soft" },
        { q: "Antonym of 'Safe'", a: "dangerous|unsafe" },
        { q: "Antonym of 'Same'", a: "different|opposite" },
        { q: "Antonym of 'Start'", a: "stop|finish|end" },
        { q: "Antonym of 'Sweet'", a: "sour|bitter" },
        { q: "Antonym of 'Thick'", a: "thin" },
        { q: "Antonym of 'True'", a: "false|fake" },
        { q: "Antonym of 'Win'", a: "lose" },
        { q: "Antonym of 'Young'", a: "old" },
        { q: "Antonym of 'Alive'", a: "dead" },
        { q: "Antonym of 'Awake'", a: "asleep|sleeping" },
        { q: "Antonym of 'Careful'", a: "careless|reckless" },
        { q: "Antonym of 'Cruel'", a: "kind|gentle|compassionate" },
        { q: "Antonym of 'Deep'", a: "shallow" },
        { q: "Antonym of 'Float'", a: "sink" },
        { q: "Antonym of 'Generous'", a: "stingy|selfish|greedy" },
        { q: "Antonym of 'Healthy'", a: "sick|ill|unhealthy" },
        { q: "Antonym of 'Import'", a: "export" }
    ],

    occupations: [
        { "q": "A person who responds to emergency medical calls outside a hospital.", "a": "paramedic" },
        { "q": "A person who tests your eyes and sells glasses.", "a": "optician" },
        { "q": "A person who studies stars, planets, and space.", "a": "astronomer" },
        { "q": "A scientist who studies living organisms.", "a": "biologist" },
        { "q": "A scientist who works with chemicals and does experiments.", "a": "chemist" },
        { "q": "A police officer who investigates crimes and finds clues.", "a": "detective" },
        { "q": "The elected head of a city or town government.", "a": "mayor" },
        { "q": "The person who is in charge of a school.", "a": "principal" },
        { "q": "A teacher of the highest rank at a university or college.", "a": "professor" },
        { "q": "A person who controls a sports match to ensure rules are followed.", "a": "referee" },
        { "q": "A person who trains an athlete or a sports team.", "a": "coach" },
        { "q": "An artist who makes figures by carving stone or wood.", "a": "sculptor" },
        { "q": "A person who writes original music.", "a": "composer" },
        { "q": "A person who leads an orchestra or a choir.", "a": "conductor" },
        { "q": "A person who guides the actors and crew in a movie.", "a": "director" },
        { "q": "A person who oversees the money and management of a movie or play.", "a": "producer" },
        { "q": "A person who corrects and prepares text for publishing.", "a": "editor" },
        { "q": "A person who changes written text from one language to another.", "a": "translator" },
        { "q": "A person who gives private lessons to a single student.", "a": "tutor" },
        { "q": "A professional who helps people deal with physical or mental problems.", "a": "therapist" },
        { "q": "A scientist who studies the human mind and behavior.", "a": "psychologist" },
        { "q": "A person who examines financial accounts to check if they are correct.", "a": "auditor" },
        { "q": "A person who buys and sells things for others, like stocks or insurance.", "a": "broker" },
        { "q": "A person who handles customer money transactions in a bank.", "a": "bank teller" },
        { "q": "A person who makes, repairs, and sells rings, necklaces, and watches.", "a": "jeweler" },
        { "q": "A person who makes and repairs things made of iron and metal.", "a": "blacksmith" },
        { "q": "A person who joins metal parts together using intense heat.", "a": "welder" },
        { "q": "A person who digs for coal, gold, or other minerals underground.", "a": "miner" },
        { "q": "A person who commands a ship or a large airplane.", "a": "captain" },
        { "q": "A scientist who studies the Earth's rocks and minerals.", "a": "geologist" },
        { "q": "A scientist who specializes in the study of plants.", "a": "botanist" },
        { "q": "A scientist who specializes in the study of animals.", "a": "zoologist" },
        { "q": "A person who creates moving images for cartoons or video games.", "a": "animator" },
        { "q": "A person who plans the look and function of clothes, interiors, or websites.", "a": "designer" },
        { "q": "A person who draws pictures for books, magazines, or advertisements.", "a": "illustrator" },
        { "q": "A worker trained with special skills to operate or repair specific equipment.", "a": "technician" },
        { "q": "A person who operates large construction machines, like cranes or bulldozers.", "a": "operator" },
        { "q": "A professional who helps you plan your meals and eat healthily.", "a": "dietitian" },
        { "q": "A doctor who specializes in caring for pregnant women and delivering babies.", "a": "obstetrician" },
        { "q": "A professional who designs, builds, and maintains gardens and parks.", "a": "landscaper" },
        { "q": "A person whose job is to build or repair roofs on buildings.", "a": "roofer" },
        { "q": "A professional who sets up and maintains computer networks.", "a": "network engineer" },
        { "q": "A person who assists a lawyer with research and organizing legal files.", "a": "paralegal" },
        { "q": "A person who mixes and serves drinks at a bar.", "a": "bartender" },
        { "q": "A person who helps actors look like their characters using cosmetics.", "a": "makeup artist" },
        { "q": "A person who organizes large events like weddings or conferences.", "a": "event planner" },
        { "q": "A person who buys products for a store or company to sell to customers.", "a": "buyer" },
        { "q": "A person who studies how society produces, distributes, and consumes goods.", "a": "economist" },
        { "q": "A person who designs the movements and steps for a dance.", "a": "choreographer" },
        { "q": "A person who travels to unknown places to learn about them.", "a": "explorer" }
],

    genderNouns: [
        { q: "Male: Actor ➔ Female: ?", a: "actress" },
        { q: "Male: Waiter ➔ Female: ?", a: "waitress" },
        { q: "Male: Nephew ➔ Female: ?", a: "niece" },
        { q: "Male: King ➔ Female: ?", a: "queen" },
        { q: "Male: Hero ➔ Female: ?", a: "heroine" },
        { q: "Female: Bride ➔ Male: ?", a: "groom|bridegroom" },
        { q: "Male: Uncle ➔ Female: ?", a: "aunt" },
        { q: "Female: Widow ➔ Male: ?", a: "widower" },
        { q: "Male: Brother ➔ Female: ?", a: "sister" },
        { q: "Male: Father ➔ Female: ?", a: "mother" },
        { q: "Male: Son ➔ Female: ?", a: "daughter" },
        { q: "Male: Grandfather ➔ Female: ?", a: "grandmother" },
        { q: "Male: Grandson ➔ Female: ?", a: "granddaughter" },
        { q: "Male: Host ➔ Female: ?", a: "hostess" },
        { q: "Male: Prince ➔ Female: ?", a: "princess" },
        { q: "Male: Emperor ➔ Female: ?", a: "empress" },
        { q: "Male: Lion ➔ Female: ?", a: "lioness" },
        { q: "Male: Tiger ➔ Female: ?", a: "tigress" },
        { q: "Male: Bull ➔ Female: ?", a: "cow" },
        { q: "Male: Rooster ➔ Female: ?", a: "hen" },
        { q: "Male: Stallion (Horse) ➔ Female: ?", a: "mare" },
        { q: "Male: Ram (Sheep) ➔ Female: ?", a: "ewe" },
        { q: "Male: Boar (Pig) ➔ Female: ?", a: "sow" },
        { q: "Male: Fox ➔ Female: ?", a: "vixen" },
        { q: "Male: Monk ➔ Female: ?", a: "nun" },
        { q: "Male: Wizard ➔ Female: ?", a: "witch" },
        { q: "Male: Duke ➔ Female: ?", a: "duchess" },
        { q: "Male: Count ➔ Female: ?", a: "countess" },
        { q: "Male: Heir ➔ Female: ?", a: "heiress" },
        { q: "Male: Lord ➔ Female: ?", a: "lady" },
        { q: "Male: Sir ➔ Female: ?", a: "madam" },
        { q: "Male: Gentleman ➔ Female: ?", a: "lady" },
        { q: "Male: Boy ➔ Female: ?", a: "girl" },
        { q: "Male: Man ➔ Female: ?", a: "woman" },
        { q: "Male: Husband ➔ Female: ?", a: "wife" },
        { q: "Male: Male ➔ Female: ?", a: "female" },
        { q: "Male: Dad ➔ Female: ?", a: "mom|mum" },
        { q: "Male: Master ➔ Female: ?", a: "mistress" },
        { q: "Male: God ➔ Female: ?", a: "goddess" },
        { q: "Male: Steward ➔ Female: ?", a: "stewardess" },
        { q: "Male: Manager ➔ Female: ?", a: "manageress" },
        { q: "Male: Mayor ➔ Female: ?", a: "mayoress" },
        { q: "Male: Prophet ➔ Female: ?", a: "prophetess" },
        { q: "Male: Priest ➔ Female: ?", a: "priestess" },
        { q: "Male: Shepherd ➔ Female: ?", a: "shepherdess" },
        { q: "Male: Peacock ➔ Female: ?", a: "peahen" },
        { q: "Male: Drake (Duck) ➔ Female: ?", a: "duck" },
        { q: "Male: Gander (Goose) ➔ Female: ?", a: "goose" },
        { q: "Male: Bachelor ➔ Female: ?", a: "spinster|bachelorette" },
        { q: "Male: Chairman ➔ Female: ?", a: "chairwoman" }
    ],

    idioms: [
        { q: "The math test was very easy. It was a piece of ______.", a: "cake" },
        { q: "I am feeling slightly ill today. I am feeling under the ______.", a: "weather" },
        { q: "Good luck on your performance! Break a ______!", a: "leg" },
        { q: "That new phone is too expensive. It costs an arm and a ______.", a: "leg" },
        { q: "She accidentally revealed the secret party. She spilled the ______.", a: "beans" },
        { q: "I am very tired, it is time to go to sleep. It's time to hit the ______.", a: "sack|bed" },
        { q: "We rarely go to the cinema, only once in a blue ______.", a: "moon" },
        { q: "Hold your ______. (Wait a moment / Be patient)", a: "horses" },
        { q: "The secret is out. You let the cat out of the ______.", a: "bag" },
        { q: "You are exactly right! You hit the nail on the ______.", a: "head" },
        { q: "To pass away or die is to kick the ______.", a: "bucket" },
        { q: "Are you joking with me? Are you pulling my ______?", a: "leg" },
        { q: "To force yourself to do something difficult is to bite the ______.", a: "bullet" },
        { q: "I barely passed the exam by the skin of my ______.", a: "teeth" },
        { q: "What's done is done. Don't cry over spilled ______.", a: "milk" },
        { q: "There is always hope. Every cloud has a silver ______.", a: "lining" },
        { q: "To do more than is expected is to go the extra ______.", a: "mile" },
        { q: "I heard a rumor about it on the ______.", a: "grapevine" },
        { q: "I have a big exam tomorrow, I need to hit the ______.", a: "books" },
        { q: "Sometimes, it's better not to know. Ignorance is ______.", a: "bliss" },
        { q: "Both people are responsible. It takes two to ______.", a: "tango" },
        { q: "Do not interfere with a situation to avoid trouble. Let sleeping dogs ______.", a: "lie" },
        { q: "You are too late for the opportunity. You missed the ______.", a: "boat" },
        { q: "You must work hard to see results. No pain, no ______.", a: "gain" },
        { q: "I can't decide which one to choose. I am on the ______.", a: "fence" },
        { q: "It happened unexpectedly, completely out of the ______.", a: "blue" },
        { q: "Rescued at the last possible moment. Saved by the ______.", a: "bell" },
        { q: "I was extremely ill yesterday. I was sick as a ______.", a: "dog" },
        { q: "Taking attention away from someone else is to steal their ______.", a: "thunder" },
        { q: "Don't believe everything completely. Take it with a grain of ______.", a: "salt" },
        { q: "It's your turn to make a decision. The ball is in your ______.", a: "court" },
        { q: "An obvious problem that no one wants to discuss. The elephant in the ______.", a: "room" },
        { q: "To support someone in good and bad times: Through thick and ______.", a: "thin" },
        { q: "To take a risk without worrying. Throw caution to the ______.", a: "wind" },
        { q: "A hopeless search for something impossible. A wild goose ______.", a: "chase" },
        { q: "To make a bad situation even worse. Adding insult to ______.", a: "injury" },
        { q: "You are looking in the wrong place. Barking up the wrong ______.", a: "tree" },
        { q: "Stop avoiding the main topic! Don't beat around the ______.", a: "bush" },
        { q: "Taking on a task that is too big. Biting off more than you can ______.", a: "chew" },
        { q: "To work late into the night. Burn the midnight ______.", a: "oil" },
        { q: "Caught in the act of doing something wrong. Caught red-______.", a: "handed" },
        { q: "That luxury car must have cost a pretty ______.", a: "penny" },
        { q: "We will deal with that problem when it happens. Cross that ______ when we come to it.", a: "bridge" },
        { q: "To do something badly to save time or money. Cutting ______.", a: "corners" },
        { q: "Arguing against something just to test it. Playing devil's ______.", a: "advocate" },
        { q: "Don't risk everything on one plan. Don't put all your eggs in one ______.", a: "basket" },
        { q: "Tell me what you are thinking. A penny for your ______.", a: "thoughts" },
        { q: "In perfect health. As fit as a ______.", a: "fiddle" },
        { q: "To trust someone even if you aren't sure. Give them the benefit of the ______.", a: "doubt" },
        { q: "To achieve two things with a single action. Kill two birds with one ______.", a: "stone" }
    ],

    superlatives: [
        { q: "Tall ➔ ?", a: "tallest" },
        { q: "Big ➔ ?", a: "biggest" },
        { q: "Good ➔ ? (Irregular)", a: "best" },
        { q: "Bad ➔ ? (Irregular)", a: "worst" },
        { q: "Happy ➔ ?", a: "happiest" },
        { q: "Beautiful ➔ ?", a: "most beautiful" },
        { q: "Far ➔ ? (Irregular)", a: "farthest|furthest" },
        { q: "Expensive ➔ ?", a: "most expensive" },
        { q: "Small ➔ ?", a: "smallest" },
        { q: "Fast ➔ ?", a: "fastest" },
        { q: "Slow ➔ ?", a: "slowest" },
        { q: "Cold ➔ ?", a: "coldest" },
        { q: "Hot ➔ ?", a: "hottest" },
        { q: "Short ➔ ?", a: "shortest" },
        { q: "Long ➔ ?", a: "longest" },
        { q: "High ➔ ?", a: "highest" },
        { q: "Low ➔ ?", a: "lowest" },
        { q: "Smart ➔ ?", a: "smartest" },
        { q: "Dumb ➔ ?", a: "dumbest" },
        { q: "Hard ➔ ?", a: "hardest" },
        { q: "Soft ➔ ?", a: "softest" },
        { q: "Loud ➔ ?", a: "loudest" },
        { q: "Quiet ➔ ?", a: "quietest" },
        { q: "Bright ➔ ?", a: "brightest" },
        { q: "Dark ➔ ?", a: "darkest" },
        { q: "Clean ➔ ?", a: "cleanest" },
        { q: "Dirty ➔ ?", a: "dirtiest" },
        { q: "Young ➔ ?", a: "youngest" },
        { q: "Old ➔ ?", a: "oldest|eldest" },
        { q: "Strong ➔ ?", a: "strongest" },
        { q: "Weak ➔ ?", a: "weakest" },
        { q: "Heavy ➔ ?", a: "heaviest" },
        { q: "Light ➔ ?", a: "lightest" },
        { q: "Thick ➔ ?", a: "thickest" },
        { q: "Thin ➔ ?", a: "thinnest" },
        { q: "Rich ➔ ?", a: "richest" },
        { q: "Poor ➔ ?", a: "poorest" },
        { q: "Cheap ➔ ?", a: "cheapest" },
        { q: "Easy ➔ ?", a: "easiest" },
        { q: "Funny ➔ ?", a: "funniest" },
        { q: "Sad ➔ ?", a: "saddest" },
        { q: "Crazy ➔ ?", a: "craziest" },
        { q: "Busy ➔ ?", a: "busiest" },
        { q: "Lazy ➔ ?", a: "laziest" },
        { q: "Angry ➔ ?", a: "angriest" },
        { q: "Dangerous ➔ ?", a: "most dangerous" },
        { q: "Careful ➔ ?", a: "most careful" },
        { q: "Difficult ➔ ?", a: "most difficult" },
        { q: "Interesting ➔ ?", a: "most interesting" },
        { q: "Important ➔ ?", a: "most important" }
    ]
};

// ==========================================
// 2. DATA AVATAR / GUARDIANS (10 JENIS & 10 LEVEL)
// ==========================================
const avatars = {
    dragon: {
        id: 'avatar_dragon', maxLevel: 10, theme: 'Grammar & Syntax',
        levels: [
            { level: 1, name: 'Noun Egg', price: 300, icon: 'fas fa-egg fa-pulse text-orange-200', desc: 'A basic naming word waiting to hatch.' },
            { level: 2, name: 'Verb Hatchling', price: 300, icon: 'fas fa-egg fa-shake text-orange-300', desc: 'It is moving! An action word is born.' },
            { level: 3, name: 'Adjective Drake', price: 300, icon: 'fas fa-dragon fa-bounce text-orange-400', desc: 'Adding colorful descriptions to sentences.' },
            { level: 4, name: 'Pronoun Flyer', price: 300, icon: 'fas fa-dragon fa-fade text-orange-500', desc: 'Replacing nouns and flying higher.' },
            { level: 5, name: 'Adverb Dragon', price: 300, icon: 'fas fa-dragon fa-beat text-red-400', desc: 'Modifying actions with incredible speed.' },
            { level: 6, name: 'Conjunction Beast', price: 300, icon: 'fas fa-dragon fa-shake text-red-500', desc: 'Connecting clauses and strong ideas.' },
            { level: 7, name: 'Syntax Commander', price: 300, icon: 'fas fa-dragon fa-bounce text-red-600', desc: 'Mastering the order of words.' },
            { level: 8, name: 'Sentence Ancient', price: 300, icon: 'fas fa-fire-alt fa-beat text-red-700', desc: 'Crafting complex and flawless sentences.' },
            { level: 9, name: 'Grammar Mythic', price: 300, icon: 'fas fa-fire-alt fa-pulse text-red-800', desc: 'The ultimate guardian of language rules.' },
            { 
                level: 10, 
                name: 'Lexical Librarian', 
                price: 300, 
                img: 'avatar_dragon.png', 
                icon: 'fas fa-dragon fa-beat legendary-avatar text-red-600 drop-shadow-lg text-2xl', 
                desc: 'The God of Grammar! Unstoppable accuracy!' 
            }
        ]
    },
    owl: {
        id: 'avatar_owl', maxLevel: 10, theme: 'Vocabulary & Spelling',
        levels: [
            { level: 1, name: 'Phonics Egg', price: 300, icon: 'fas fa-egg fa-pulse text-blue-200', desc: 'The foundation of sounds and letters.' },
            { level: 2, name: 'Syllable Egg', price: 300, icon: 'fas fa-egg fa-shake text-blue-300', desc: 'Vibrating with word parts.' },
            { level: 3, name: 'Vocab Owlet', price: 300, icon: 'fas fa-crow fa-bounce text-blue-400', desc: 'Learning its first new words.' },
            { level: 4, name: 'Spelling Owl', price: 300, icon: 'fas fa-crow fa-fade text-blue-500', desc: 'Never makes a typo.' },
            { level: 5, name: 'Lexicon Reader', price: 300, icon: 'fas fa-crow fa-beat text-indigo-400', desc: 'Expanding its personal dictionary.' },
            { level: 6, name: 'Synonym Master', price: 300, icon: 'fas fa-feather fa-shake text-indigo-500', desc: 'Always knows another word for it.' },
            { level: 7, name: 'Antonym Guardian', price: 300, icon: 'fas fa-feather fa-bounce text-indigo-600', desc: 'Master of opposites and contrasts.' },
            { level: 8, name: 'Thesaurus Ancient', price: 300, icon: 'fas fa-feather-alt fa-beat text-indigo-700', desc: 'Holds thousands of brilliant words.' },
            { level: 9, name: 'Etymology Mythic', price: 300, icon: 'fas fa-feather-alt fa-pulse text-indigo-800', desc: 'Knows the true origin of all languages.' },
            { 
                level: 10, 
                name: 'Quantum Poet', 
                price: 300, 
                img: 'avatar_owl.png',
                icon: 'fas fa-feather-alt fa-beat legendary-avatar text-indigo-500 drop-shadow-lg text-2xl', 
                desc: 'The Guardian of the Ultimate Dictionary!' 
            }
        ]
    },
    bot: {
        id: 'avatar_bot', maxLevel: 10, theme: 'Punctuation & Mechanics',
        levels: [
            { level: 1, name: 'Comma Cube', price: 300, icon: 'fas fa-box fa-pulse text-gray-300', desc: 'A basic pause in the sentence.' },
            { level: 2, name: 'Period Processor', price: 300, icon: 'fas fa-box fa-shake text-gray-400', desc: 'Ending sentences with certainty.' },
            { level: 3, name: 'Hyphen Bot', price: 300, icon: 'fas fa-microchip fa-bounce text-teal-300', desc: 'Connecting compound words.' },
            { level: 4, name: 'Apostrophe Mecha', price: 300, icon: 'fas fa-robot fa-fade text-teal-400', desc: 'Showing ownership and contractions.' },
            { level: 5, name: 'Quotation Bot', price: 300, icon: 'fas fa-robot fa-beat text-teal-500', desc: 'Capturing exact dialogue safely.' },
            { level: 6, name: 'Colon Cyborg', price: 300, icon: 'fas fa-robot fa-shake text-teal-600', desc: 'Introducing lists and explanations.' },
            { level: 7, name: 'Semicolon Armor', price: 300, icon: 'fas fa-robot fa-bounce text-blue-500', desc: 'Linking independent clauses like a pro.' },
            { level: 8, name: 'Exclamation Ancient', price: 300, icon: 'fas fa-user-astronaut fa-beat text-blue-600', desc: 'Expressing strong emotions!' },
            { level: 9, name: 'Mechanics Mythic', price: 300, icon: 'fas fa-user-astronaut fa-pulse text-purple-600', desc: 'Scanning text for perfect formatting.' },
            { 
                level: 10, 
                name: 'Holographic Linguist', 
                price: 300, 
                img: 'avatar_bot.png',
                icon: 'fas fa-user-astronaut fa-spin legendary-avatar text-purple-500 drop-shadow-lg text-2xl', 
                desc: 'The Flawless Proofreading Titan!' 
            }
        ]
    },
    wolf: {
        id: 'avatar_wolf', maxLevel: 10, theme: 'Speaking & Fluency',
        levels: [
            { level: 1, name: 'Whisper Paw', price: 300, icon: 'fas fa-paw fa-pulse text-cyan-200', desc: 'Practicing quiet pronunciation.' },
            { level: 2, name: 'Echo Paw', price: 300, icon: 'fas fa-paw fa-shake text-cyan-300', desc: 'Repeating native sounds perfectly.' },
            { level: 3, name: 'Vocal Pup', price: 300, icon: 'fas fa-dog fa-bounce text-cyan-400', desc: 'Speaking short phrases with joy.' },
            { level: 4, name: 'Chatter Wolf', price: 300, icon: 'fas fa-dog fa-fade text-cyan-500', desc: 'Engaging in small talk.' },
            { level: 5, name: 'Dialogue Hunter', price: 300, icon: 'fas fa-dog fa-beat text-blue-400', desc: 'Mastering conversational English.' },
            { level: 6, name: 'Fluency Alpha', price: 300, icon: 'fas fa-dog fa-shake text-blue-500', desc: 'Speaking smoothly without hesitation.' },
            { level: 7, name: 'Accent Master', price: 300, icon: 'fas fa-dog fa-bounce text-blue-600', desc: 'Adapting to different English intonations.' },
            { level: 8, name: 'Articulation Ancient', price: 300, icon: 'fas fa-moon fa-beat text-blue-700', desc: 'Clear and powerful speech delivery.' },
            { level: 9, name: 'Eloquence Mythic', price: 300, icon: 'fas fa-moon fa-pulse text-blue-800', desc: 'Persuading the pack with words.' },
            { 
                level: 10, 
                name: 'Aetheric Scribe', 
                price: 300, 
                img: 'avatar_wolf.png',
                icon: 'fas fa-moon fa-beat legendary-avatar text-cyan-500 drop-shadow-lg text-2xl', 
                desc: 'The Legendary Voice of the Forest!' 
            }
        ]
    },
    phoenix: {
        id: 'avatar_phoenix', maxLevel: 10, theme: 'Writing & Composition',
        levels: [
            { level: 1, name: 'Idea Feather', price: 300, icon: 'fas fa-fire fa-pulse text-yellow-300', desc: 'A tiny spark of a writing topic.' },
            { level: 2, name: 'Drafting Feather', price: 300, icon: 'fas fa-fire fa-shake text-yellow-400', desc: 'Putting first thoughts on paper.' },
            { level: 3, name: 'Outline Chick', price: 300, icon: 'fas fa-dove fa-bounce text-orange-300', desc: 'Organizing the essay structure.' },
            { level: 4, name: 'Paragraph Bird', price: 300, icon: 'fas fa-dove fa-fade text-orange-400', desc: 'Writing strong topic sentences.' },
            { level: 5, name: 'Essay Flier', price: 300, icon: 'fas fa-dove fa-beat text-orange-500', desc: 'Connecting paragraphs with transitions.' },
            { level: 6, name: 'Revision Bird', price: 300, icon: 'fas fa-dove fa-shake text-red-400', desc: 'Improving and rewriting better drafts.' },
            { level: 7, name: 'Article Master', price: 300, icon: 'fas fa-dove fa-bounce text-red-500', desc: 'Publishing captivating articles.' },
            { level: 8, name: 'Manuscript Ancient', price: 300, icon: 'fas fa-fire-alt fa-beat text-red-600', desc: 'A legend in creative writing.' },
            { level: 9, name: 'Bestseller Mythic', price: 300, icon: 'fas fa-fire-alt fa-pulse text-red-700', desc: 'Words that live forever.' },
            { 
                level: 10, 
                name: 'Data Arcanist', 
                price: 300, 
                img: 'avatar_phoenix.png',
                icon: 'fas fa-fire-alt fa-beat legendary-avatar text-yellow-500 drop-shadow-lg text-2xl', 
                desc: 'The Immortal Master of Stories!' 
            }
        ]
    },
    leviathan: {
        id: 'avatar_leviathan', maxLevel: 10, theme: 'Reading & Comprehension',
        levels: [
            { level: 1, name: 'Context Drop', price: 300, icon: 'fas fa-tint fa-pulse text-blue-200', desc: 'Guessing meaning from context.' },
            { level: 2, name: 'Skimming Drop', price: 300, icon: 'fas fa-tint fa-shake text-blue-300', desc: 'Reading fast to get the main idea.' },
            { level: 3, name: 'Scanning Fish', price: 300, icon: 'fas fa-fish fa-bounce text-teal-300', desc: 'Looking closely for specific facts.' },
            { level: 4, name: 'Inference Spirit', price: 300, icon: 'fas fa-fish fa-fade text-teal-400', desc: 'Reading between the lines.' },
            { level: 5, name: 'Summary Swimmer', price: 300, icon: 'fas fa-fish fa-beat text-teal-500', desc: 'Condensing long texts easily.' },
            { level: 6, name: 'Analysis Spirit', price: 300, icon: 'fas fa-fish fa-shake text-teal-600', desc: 'Breaking down complex paragraphs.' },
            { level: 7, name: 'Comprehension Master', price: 300, icon: 'fas fa-water fa-bounce text-blue-500', desc: 'Understanding the deepest texts.' },
            { level: 8, name: 'Literature Ancient', price: 300, icon: 'fas fa-water fa-beat text-blue-600', desc: 'Devouring classic novels.' },
            { level: 9, name: 'Epic Mythic', price: 300, icon: 'fas fa-water fa-pulse text-blue-700', desc: 'Mastering poetry and prose.' },
            { 
                level: 10, 
                name: 'Nanotech Bard', 
                price: 300, 
                img: 'avatar_leviathan.png',
                icon: 'fas fa-water fa-beat legendary-avatar text-blue-500 drop-shadow-lg text-2xl', 
                desc: 'An unstoppable wave of knowledge!' 
            }
        ]
    },
    unicorn: {
        id: 'avatar_unicorn', maxLevel: 10, theme: 'Figurative Language',
        levels: [
            { level: 1, name: 'Rhyme Dust', price: 300, icon: 'fas fa-star fa-pulse text-pink-200', desc: 'Words that sound magically alike.' },
            { level: 2, name: 'Simile Dust', price: 300, icon: 'fas fa-star fa-shake text-pink-300', desc: 'As bright as a glowing star.' },
            { level: 3, name: 'Metaphor Pony', price: 300, icon: 'fas fa-horse fa-bounce text-pink-400', desc: 'A pony that IS a star.' },
            { level: 4, name: 'Personification Pony', price: 300, icon: 'fas fa-horse fa-fade text-pink-500', desc: 'Making non-human things alive.' },
            { level: 5, name: 'Idiom Mystic', price: 300, icon: 'fas fa-horse fa-beat text-purple-400', desc: 'Raining cats and dogs!' },
            { level: 6, name: 'Hyperbole Unicorn', price: 300, icon: 'fas fa-horse fa-shake text-purple-500', desc: 'The fastest creature in a million years.' },
            { level: 7, name: 'Alliteration Master', price: 300, icon: 'fas fa-horse-head fa-bounce text-purple-600', desc: 'Creating cool consonant combos.' },
            { level: 8, name: 'Poetic Ancient', price: 300, icon: 'fas fa-horse-head fa-beat text-purple-700', desc: 'Master of verses and stanzas.' },
            { level: 9, name: 'Inspiration Mythic', price: 300, icon: 'fas fa-horse-head fa-pulse text-pink-600', desc: 'Sparking creative writing ideas.' },
            { 
                level: 10, 
                name: 'Cosmic Narrator', 
                price: 300, 
                img: 'avatar_unicorn.png',
                icon: 'fas fa-horse-head fa-beat legendary-avatar text-pink-500 drop-shadow-lg text-2xl', 
                desc: 'The most beautiful magic in literature!' 
            }
        ]
    },
    golem: {
        id: 'avatar_golem', maxLevel: 10, theme: 'Tenses & Structure',
        levels: [
            { level: 1, name: 'Past Pebble', price: 300, icon: 'fas fa-circle fa-pulse text-gray-400', desc: 'Actions that already happened.' },
            { level: 2, name: 'Present Pebble', price: 300, icon: 'fas fa-circle fa-shake text-gray-500', desc: 'Actions happening right now.' },
            { level: 3, name: 'Future Rock', price: 300, icon: 'fas fa-cube fa-bounce text-gray-600', desc: 'Plans that will happen tomorrow.' },
            { level: 4, name: 'Continuous Stone', price: 300, icon: 'fas fa-cube fa-fade text-gray-700', desc: 'Rolling with the -ing verbs.' },
            { level: 5, name: 'Perfect Tense Guardian', price: 300, icon: 'fas fa-cubes fa-beat text-gray-800', desc: 'Has mastered the past participles.' },
            { level: 6, name: 'Active Voice Iron', price: 300, icon: 'fas fa-cubes fa-shake text-gray-900', desc: 'Direct, clear, and unbreakable.' },
            { level: 7, name: 'Passive Voice Golem', price: 300, icon: 'fas fa-mountain fa-bounce text-gray-600', desc: 'Actions are being done to it.' },
            { level: 8, name: 'Conditional Ancient', price: 300, icon: 'fas fa-mountain fa-beat text-gray-700', desc: 'If you study, you will succeed.' },
            { level: 9, name: 'Structure Mythic', price: 300, icon: 'fas fa-mountain fa-pulse text-gray-800', desc: 'A walking mountain of solid grammar.' },
            { 
                level: 10, 
                name: 'Cyber Etymologist', 
                price: 300, 
                img: 'avatar_golem.png',
                icon: 'fas fa-mountain fa-shake legendary-avatar text-gray-900 drop-shadow-lg text-2xl', 
                desc: 'The Unshakeable Earth Shaker!' 
            }
        ]
    },
    fairy: {
        id: 'avatar_fairy', maxLevel: 10, theme: 'Listening & Communication',
        levels: [
            { level: 1, name: 'Sound Seedling', price: 300, icon: 'fas fa-seedling fa-pulse text-green-300', desc: 'Catching the first English sounds.' },
            { level: 2, name: 'Tune Sprout', price: 300, icon: 'fas fa-seedling fa-shake text-green-400', desc: 'Listening to the rhythm of sentences.' },
            { level: 3, name: 'Audio Sprite', price: 300, icon: 'fas fa-leaf fa-bounce text-green-500', desc: 'Understanding short instructions.' },
            { level: 4, name: 'Podcast Sprite', price: 300, icon: 'fas fa-leaf fa-fade text-green-600', desc: 'Enjoying English stories in the wind.' },
            { level: 5, name: 'Conversation Fairy', price: 300, icon: 'fas fa-tree fa-beat text-green-700', desc: 'Planting ideas through dialogue.' },
            { level: 6, name: 'Active Listener', price: 300, icon: 'fas fa-tree fa-shake text-green-800', desc: 'Paying close attention to details.' },
            { level: 7, name: 'Nuance Master', price: 300, icon: 'fas fa-tree fa-bounce text-teal-600', desc: 'Understanding tone and emotion.' },
            { level: 8, name: 'Interpreter Ancient', price: 300, icon: 'fas fa-tree fa-beat text-teal-700', desc: 'Translating thoughts seamlessly.' },
            { level: 9, name: 'Polyglot Mythic', price: 300, icon: 'fas fa-tree fa-pulse text-teal-800', desc: 'Glowing with communication magic.' },
            { 
                level: 10, 
                name: 'Bionic Botanis & Grammarian ', 
                price: 300, 
                img: 'avatar_fairy.png',
                icon: 'fas fa-tree fa-beat legendary-avatar text-green-500 drop-shadow-lg text-2xl', 
                desc: 'The Queen of Global Connections!' 
            }
        ]
    },
    lion: {
        id: 'avatar_lion', maxLevel: 10, theme: 'Debate & Persuasion',
        levels: [
            { level: 1, name: 'Claim Kitten', price: 300, icon: 'fas fa-bolt fa-pulse text-yellow-200', desc: 'Making a tiny but valid point.' },
            { level: 2, name: 'Reason Kitten', price: 300, icon: 'fas fa-bolt fa-shake text-yellow-300', desc: 'Backing up claims with "because".' },
            { level: 3, name: 'Logic Cub', price: 300, icon: 'fas fa-cat fa-bounce text-yellow-400', desc: 'Thinking fast and making sense.' },
            { level: 4, name: 'Evidence Volt Cat', price: 300, icon: 'fas fa-cat fa-fade text-yellow-500', desc: 'Running with facts and statistics.' },
            { level: 5, name: 'Argument Cat', price: 300, icon: 'fas fa-cat fa-beat text-orange-400', desc: 'Building strong, shocking cases.' },
            { level: 6, name: 'Rebuttal Lion', price: 300, icon: 'fas fa-cat fa-shake text-orange-500', desc: 'Countering opposing views with thunder.' },
            { level: 7, name: 'Persuasion Master', price: 300, icon: 'fas fa-crown fa-bounce text-yellow-500', desc: 'Convincing the crowd easily.' },
            { level: 8, name: 'Rhetoric Ancient', price: 300, icon: 'fas fa-crown fa-beat text-yellow-600', desc: 'A legendary speaker of the sky.' },
            { level: 9, name: 'Debate Mythic', price: 300, icon: 'fas fa-crown fa-pulse text-orange-600', desc: 'Summoning lightning-fast responses.' },
            { 
                level: 10, 
                name: 'Aether Historian', 
                price: 300, 
                img: 'avatar_lion.png',
                icon: 'fas fa-crown fa-beat legendary-avatar text-yellow-400 drop-shadow-lg text-2xl', 
                desc: 'The Absolute King of the Stage!' 
            }
        ]
    }
};

// ==========================================
// DATA KEDAI BADGE (BADGES SHOP)
// ==========================================
const shopBadges = [
    // ---------------------------------------------------------
    // 1. GAME BADGES (Tiada syarat, sentiasa ada di kedai)
    // Harga: 500 (Boleh tukar mengikut harga asal anda)
    // ---------------------------------------------------------
    { id: "gb_01", name: "Guessing Word Badge", icon: "fas fa-question-circle", price: 500, type: "game", tier: "common", condition: "none" },
    { id: "gb_02", name: "Word Scramble Badge", icon: "fas fa-random", price: 500, type: "game", tier: "common", condition: "none" },
    { id: "gb_03", name: "Synonym Badge", icon: "fas fa-equals", price: 500, type: "game", tier: "common", condition: "none" },
    { id: "gb_04", name: "Antonym Badge", icon: "fas fa-exchange-alt", price: 500, type: "game", tier: "common", condition: "none" },
    { id: "gb_05", name: "Missing Letter Badge", icon: "fas fa-search", price: 500, type: "game", tier: "common", condition: "none" },
    { id: "gb_06", name: "Past Tense Badge", icon: "fas fa-history", price: 500, type: "game", tier: "common", condition: "none" },
    { id: "gb_07", name: "Plural Form Badge", icon: "fas fa-copy", price: 500, type: "game", tier: "common", condition: "none" },
    { id: "gb_08", name: "Correct Spelling Badge", icon: "fas fa-spell-check", price: 500, type: "game", tier: "common", condition: "none" },
    { id: "gb_09", name: "Occupation Badge", icon: "fas fa-user-md", price: 500, type: "game", tier: "common", condition: "none" },
    { id: "gb_10", name: "Gender Noun Badge", icon: "fas fa-venus-mars", price: 500, type: "game", tier: "common", condition: "none" },
    { id: "gb_11", name: "Popular Idioms Badge", icon: "fas fa-comments", price: 500, type: "game", tier: "common", condition: "none" },
    { id: "gb_12", name: "Superlatives Badge", icon: "fas fa-trophy", price: 500, type: "game", tier: "common", condition: "none" },

    // ---------------------------------------------------------
    // 2. ACHIEVEMENT BADGES (Terkunci sehingga syarat dipenuhi)
    // ---------------------------------------------------------
    
    // --- TIER COMMON (Harga: 1,000 coins) ---
    { id: "ab_c1", name: "First Try Badge", desc: "Main mana-mana 1 permainan.", icon: "fas fa-seedling", price: 1000, type: "achievement", tier: "common", reqType: "total_games", reqValue: 1 },
    { id: "ab_c2", name: "High Five Badge", desc: "Main 5 permainan keseluruhan.", icon: "fas fa-hand-paper", price: 1000, type: "achievement", tier: "common", reqType: "total_games", reqValue: 5 },
    { id: "ab_c3", name: "Quick Learner Badge", desc: "Dapat 1 markah penuh (Perfect Score).", icon: "fas fa-star", price: 1000, type: "achievement", tier: "common", reqType: "perfect_scores", reqValue: 1 },
    { id: "ab_c4", name: "Level 5 Guardian Badge", desc: "Capai Level 5.", icon: "fas fa-arrow-up", price: 1000, type: "achievement", tier: "common", reqType: "level", reqValue: 5 },
    { id: "ab_c5", name: "Pocket Money Badge", desc: "Kumpul jumlah 5,000 coins.", icon: "fas fa-coins", price: 1000, type: "achievement", tier: "common", reqType: "total_coins", reqValue: 5000 },

    // --- TIER RARE (Harga: 2,000 coins) ---
    { id: "ab_r1", name: "Regular Player Badge", desc: "Main 20 permainan keseluruhan.", icon: "fas fa-gamepad", price: 2000, type: "achievement", tier: "rare", reqType: "total_games", reqValue: 20 },
    { id: "ab_r2", name: "Explorer Badge", desc: "Main 6 jenis permainan berbeza.", icon: "fas fa-map", price: 2000, type: "achievement", tier: "rare", reqType: "unique_games", reqValue: 6 },
    { id: "ab_r3", name: "Hat-trick Badge", desc: "Dapat 3 markah penuh (Perfect Score).", icon: "fas fa-hat-wizard", price: 2000, type: "achievement", tier: "rare", reqType: "perfect_scores", reqValue: 3 },
    { id: "ab_r4", name: "Level 15 Guardian Badge", desc: "Capai Level 15.", icon: "fas fa-shield-alt", price: 2000, type: "achievement", tier: "rare", reqType: "level", reqValue: 15 },
    { id: "ab_r5", name: "Coin Collector Badge", desc: "Kumpul jumlah 20,000 coins.", icon: "fas fa-piggy-bank", price: 2000, type: "achievement", tier: "rare", reqType: "total_coins", reqValue: 20000 },

    // --- TIER EPIC (Harga: 5,000 coins) ---
    { id: "ab_e1", name: "Veteran Badge", desc: "Main 50 permainan keseluruhan.", icon: "fas fa-medal", price: 5000, type: "achievement", tier: "epic", reqType: "total_games", reqValue: 50 },
    { id: "ab_e2", name: "Adventurer Badge", desc: "Main 10 jenis permainan berbeza.", icon: "fas fa-compass", price: 5000, type: "achievement", tier: "epic", reqType: "unique_games", reqValue: 10 },
    { id: "ab_e3", name: "Flawless Badge", desc: "Dapat 8 markah penuh (Perfect Score).", icon: "fas fa-gem", price: 5000, type: "achievement", tier: "epic", reqType: "perfect_scores", reqValue: 8 },
    { id: "ab_e4", name: "Level 30 Guardian Badge", desc: "Capai Level 30.", icon: "fas fa-chess-knight", price: 5000, type: "achievement", tier: "epic", reqType: "level", reqValue: 30 },
    { id: "ab_e5", name: "Wealthy Student Badge", desc: "Kumpul jumlah 50,000 coins.", icon: "fas fa-money-bill-wave", price: 5000, type: "achievement", tier: "epic", reqType: "total_coins", reqValue: 50000 },

    // --- TIER LEGENDARY (Harga: 10,000 coins) ---
    { id: "ab_l1", name: "The Addict Badge", desc: "Main 100 permainan keseluruhan.", icon: "fas fa-fire", price: 10000, type: "achievement", tier: "legendary", reqType: "total_games", reqValue: 100 },
    { id: "ab_l2", name: "Perfectionist Badge", desc: "Dapat markah penuh untuk SEMUA 12 permainan.", icon: "fas fa-crown", price: 10000, type: "achievement", tier: "legendary", reqType: "perfect_scores", reqValue: 12 },
    { id: "ab_l3", name: "Level 50 Master Badge", desc: "Capai Level 50.", icon: "fas fa-dragon", price: 10000, type: "achievement", tier: "legendary", reqType: "level", reqValue: 50 },
    { id: "ab_l4", name: "Millionaire Badge", desc: "Kumpul jumlah 100,000 coins.", icon: "fas fa-sack-dollar", price: 10000, type: "achievement", tier: "legendary", reqType: "total_coins", reqValue: 100000 },
    { id: "ab_l5", name: "The Legend Badge", desc: "Capai Level 100 (Max Level).", icon: "fas fa-infinity", price: 10000, type: "achievement", tier: "legendary", reqType: "level", reqValue: 100 }
];
// ------------------------------------------
    // KATEGORI: EDU SHOP (BARANGAN SEKOLAH / ALAT TULIS)
    // ------------------------------------------
        const shopItems = [
    { id: 'edu_eraser', category: 'edu', name: 'Eraser', price: 100, icon: 'fas fa-eraser text-pink-400', desc: 'A basic pink eraser to fix tiny mistakes.' },
    { id: 'edu_pencil', category: 'edu', name: 'Pencil', price: 150, icon: 'fas fa-pencil-alt text-yellow-500', desc: 'A sharp 2B pencil for writing down answers.' },
    { id: 'edu_pen', category: 'edu', name: 'Pen', price: 200, icon: 'fas fa-pen text-blue-600', desc: 'A smooth blue pen for confident writing.' },
    { id: 'edu_ruler', category: 'edu', name: 'Ruler', price: 250, icon: 'fas fa-ruler text-green-500', desc: 'Keep your lines straight and neat.' },
    { id: 'edu_sharpener', category: 'edu', name: 'Sharpener', price: 300, icon: 'fas fa-cube text-red-500', desc: 'Keep your pencils sharp and ready.' },
    { id: 'edu_exercise_book', category: 'edu', name: 'Exercise Book', price: 400, icon: 'fas fa-book-open text-blue-400', desc: 'A standard book for daily grammar practice.' },
    { id: 'edu_color_paper', category: 'edu', name: 'Color Paper', price: 500, icon: 'fas fa-copy text-pink-500', desc: 'Bright colorful papers for your art projects.' },
    { id: 'edu_notebook', category: 'edu', name: 'Notebook', price: 600, icon: 'fas fa-book text-indigo-500', desc: 'A premium notebook with thick pages.' },
    { id: 'edu_drawing_book', category: 'edu', name: 'Drawing Book', price: 700, icon: 'fas fa-book-reader text-orange-400', desc: 'A large book for your creative ideas.' },
    { id: 'edu_pencil_box', category: 'edu', name: 'Pencil Box', price: 1800, icon: 'fas fa-box text-purple-500', desc: 'A cool box to store all your stationery.' },
    { id: 'edu_adv_sharpener', category: 'edu', name: 'Advance Sharpener', price: 1850, icon: 'fas fa-cogs text-gray-700', desc: 'An automatic sharpener. Fast and easy!' },
    { id: 'edu_pencil_color', category: 'edu', name: 'Pencil Color', price: 1500, icon: 'fas fa-pencil-ruler text-yellow-600', desc: 'A set of 24 beautiful colored pencils.' },
    { id: 'edu_water_color', category: 'edu', name: 'Water Color', price: 2000, icon: 'fas fa-paint-brush text-teal-500', desc: 'Premium water colors for a masterpiece!' }
];

// ==========================================
// 3. DATA PENCAPAIAN (ACHIEVEMENTS)
// ==========================================
const ACHIEVEMENTS_LIST = [
    // --- Category 1: Leaderboard & Academics ---
    { id: "ach_01", name: "First Steps", description: "Collect 100 Total Score.", titleReward: "The Alphabet Apprentice", coinReward: 20 },
    { id: "ach_02", name: "Brainiac", description: "Collect 1,000 Total Score.", titleReward: "The Grammar Scholar", coinReward: 20 },
    { id: "ach_03", name: "Walking Dictionary", description: "Collect 5,000 Total Score.", titleReward: "The Vocabulary Virtuoso", coinReward: 20 },
    { id: "ach_04", name: "Einstein's Heir", description: "Collect 10,000 Total Score.", titleReward: "The Literary Mastermind", coinReward: 20 },
    { id: "ach_05", name: "Flawless English", description: "Get a Perfect Score in any 5 games.", titleReward: "The Perfect Proofreader", coinReward: 20 },

    // --- Category 2: Challenge Mode ---
    { id: "ach_06", name: "Brave Speaker", description: "Send your first challenge to a friend.", titleReward: "The Debate Challenger", coinReward: 20 },
    { id: "ach_07", name: "First Victory", description: "Win a friend's challenge for the first time.", titleReward: "The Fluent Victor", coinReward: 20 },
    { id: "ach_08", name: "Unbeatable", description: "Win 10 challenges overall.", titleReward: "The Spelling Champion", coinReward: 20 },
    { id: "ach_09", name: "Worthy Opponent", description: "Tie a friend's score in challenge mode.", titleReward: "The Peer Reviewer", coinReward: 20 },

    // --- Category 3: Economy & Wealth ---
    { id: "ach_10", name: "First Paycheck", description: "Collect 1,000 Coins.", titleReward: "The Knowledge Seeker", coinReward: 20 },
    { id: "ach_11", name: "Big Spender", description: "Spend 5,000 Coins in the Shop.", titleReward: "The Resource Investor", coinReward: 20 },
    { id: "ach_12", name: "Rolling in Gold", description: "Collect 20,000 Coins overall.", titleReward: "The Wealthy Wordsmith", coinReward: 20 },

    // --- Category 4: Avatar Collection ---
    { id: "ach_13", name: "New Look", description: "Buy your first avatar.", titleReward: "The Style Articulator", coinReward: 20 },
    { id: "ach_14", name: "Wardrobe Full", description: "Collect 5 different avatars.", titleReward: "The Guardian Collector", coinReward: 20 },
    { id: "ach_15", name: "Max Power", description: "Upgrade any avatar to Level 10 (Max Level).", titleReward: "The Syntax Sage", coinReward: 20 },
    { id: "ach_16", name: "Guardian Master", description: "Buy all animal or fantasy-themed avatars.", titleReward: "The Lore Keeper", coinReward: 20 },

    // --- Category 5: Dedication & Events ---
    { id: "ach_17", name: "Event Hunter", description: "Play during a Limited Time Event.", titleReward: "The Active Participant", coinReward: 20 },
    { id: "ach_18", name: "Night Owl", description: "Play a game after 10 PM.", titleReward: "The Midnight Reader", coinReward: 20 },
    { id: "ach_19", name: "Early Bird", description: "Play a game before 7 AM.", titleReward: "The Morning Orator", coinReward: 20 },

    // --- Category 6: Persistence & Streaks ---
    { id: "ach_20", name: "Weekend Warrior", description: "Play at least one game on a Saturday or Sunday.", titleReward: "The Weekend Writer", coinReward: 20 },
    { id: "ach_21", name: "3-Day Streak", description: "Play at least one game for 3 consecutive days.", titleReward: "The Consistent Student", coinReward: 20 },
    { id: "ach_22", name: "1-Week Streak", description: "Play for 7 consecutive days without failing.", titleReward: "The Dedicated Linguist", coinReward: 20 },
    { id: "ach_23", name: "Marathoner", description: "Complete 5 different games in a single day.", titleReward: "The Language Marathoner", coinReward: 20 },

    // --- Category 7: Game Mastery ---
    { id: "ach_24", name: "The Explorer", description: "Play all 12 games at least once.", titleReward: "The Syllabus Explorer", coinReward: 20 },
    { id: "ach_25", name: "Jack of All Trades", description: "Score at least 50 points in each of the 12 games.", titleReward: "The Polymath", coinReward: 20 },
    { id: "ach_26", name: "Comeback Kid", description: "Get a Perfect Score in a game you previously scored low in.", titleReward: "The Resilient Reviser", coinReward: 20 },
    { id: "ach_27", name: "Triple Threat", description: "Get a Perfect Score in 3 different games.", titleReward: "The English Prodigy", coinReward: 20 },

    // --- Category 8: Social & Advanced Challenges ---
    { id: "ach_28", name: "Friendly Rival", description: "Send 10 challenge codes to friends.", titleReward: "The Study Buddy", coinReward: 20 },
    { id: "ach_29", name: "Challenge Addict", description: "Complete 50 challenges overall.", titleReward: "The Forum Debater", coinReward: 20 },
    { id: "ach_30", name: "Good Sport", description: "Lose 5 challenges. Don't give up!", titleReward: "The Gracious Learner", coinReward: 20 },
    { id: "ach_31", name: "Close Call", description: "Win a challenge with a narrow margin of 1 to 5 points.", titleReward: "The Sharp Thinker", coinReward: 20 },
    { id: "ach_32", name: "Academic Comeback", description: "Defeat a friend who previously beat your record.", titleReward: "The Academic Redeemer", coinReward: 20 },

    // --- Category 9: Advanced Inventory ---
    { id: "ach_33", name: "Window Shopper", description: "Open the Shop menu 20 times.", titleReward: "The Curious Browser", coinReward: 20 },
    { id: "ach_34", name: "Avid Collector", description: "Collect 10 different avatars in your inventory.", titleReward: "The Archive Master", coinReward: 20 },
    { id: "ach_35", name: "Elite Squad", description: "Upgrade 3 different avatars to Level 10 (Max Level).", titleReward: "The Dean of Guardians", coinReward: 20 },
    { id: "ach_36", name: "Loyal Companion", description: "Equip the same avatar for 7 consecutive days.", titleReward: "The Steadfast Scholar", coinReward: 20 },

    // --- Category 10: Special Events & Hidden ---
    { id: "ach_37", name: "Merdeka Scholar", description: "Log in and play on August 31st.", titleReward: "The Patriotic Poet", coinReward: 20 },
    { id: "ach_38", name: "Holiday Gamer", description: "Log in and play during the December holidays.", titleReward: "The Festive Storyteller", coinReward: 20 },
    { id: "ach_39", name: "First Arrival", description: "Log in to the Game Hub for the first time.", titleReward: "The Freshman", coinReward: 20 },
    { id: "ach_40", name: "Secret Finder", description: "??? (Discover the hidden secret in the Game Hub)", titleReward: "The Context Detective", coinReward: 20 }
];

// ==========================================
// 3. DATA LEVEL & PANGKAT (1 - 150)
// ==========================================
const levelRanks = [
    { minLevel: 1,  maxLevel: 10, title: "Novice",       icon: "🌱", colorClass: "text-green-500" },
    { minLevel: 11, maxLevel: 20, title: "Apprentice",   icon: "📘", colorClass: "text-blue-500" },
    { minLevel: 21, maxLevel: 30, title: "Explorer",     icon: "🔍", colorClass: "text-teal-500" },
    { minLevel: 31, maxLevel: 40, title: "Defender",     icon: "🛡️", colorClass: "text-indigo-500" },
    { minLevel: 41, maxLevel: 50, title: "Scholar",      icon: "📜", colorClass: "text-purple-500" },
    { minLevel: 51, maxLevel: 60, title: "Mystic",       icon: "🧙‍♂️", colorClass: "text-fuchsia-500" },
    { minLevel: 61, maxLevel: 70, title: "Champion",     icon: "⚔️", colorClass: "text-red-500" },
    { minLevel: 71, maxLevel: 80, title: "Wordsmith",    icon: "🖋️", colorClass: "text-orange-500" },
    { minLevel: 81, maxLevel: 90, title: "Grandmaster",  icon: "👑", colorClass: "text-yellow-400 drop-shadow-md" },
    { minLevel: 91, maxLevel: 100, title: "Legend",      icon: "🌟", colorClass: "text-amber-400 drop-shadow-[0_0_8px_rgba(251,191,36,0.8)] animate-pulse" },
    
    // --- ERA HARDCORE (END-GAME TIERS) ---
    { minLevel: 101, maxLevel: 110, title: "Mythic",     icon: "🦄", colorClass: "text-pink-400 drop-shadow-[0_0_10px_rgba(244,114,182,0.8)]" },
    { minLevel: 111, maxLevel: 120, title: "Oracle",     icon: "🔮", colorClass: "text-cyan-400 drop-shadow-[0_0_12px_rgba(34,211,238,0.9)] animate-pulse" },
    { minLevel: 121, maxLevel: 130, title: "Celestial",  icon: "🌌", colorClass: "text-blue-400 drop-shadow-[0_0_15px_rgba(96,165,250,1)] animate-pulse" },
    { minLevel: 131, maxLevel: 140, title: "Ascendant",  icon: "🕊️", colorClass: "text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-emerald-400 drop-shadow-lg animate-pulse font-extrabold" },
    { minLevel: 141, maxLevel: 150, title: "Omniscient", icon: "👁️‍🗨️", colorClass: "text-transparent bg-clip-text bg-gradient-to-r from-fuchsia-500 via-red-500 to-orange-500 drop-shadow-[0_0_20px_rgba(217,70,239,1)] animate-pulse font-black" }
];
