// ==========================================
// 1. DATA SOALAN PERMAINAN (GAME DATA)
// ==========================================
const gameData = {
missing: [
        { q: "A P P _ E (A red fruit)", a: "l" },
        { q: "S C _ O O L (A place to study)", a: "h" },
        { q: "T _ A C H E R (Person who teaches you)", a: "e" },
        { q: "B A N _ N A (A yellow fruit)", a: "a" },
        { q: "O R _ N G E (A citrus fruit)", a: "a" },
        { q: "C _ M P U T E R (A machine with a screen)", a: "o" },
        { q: "M _ T H E R (Your female parent)", a: "o" },
        { q: "F _ T H E R (Your male parent)", a: "a" },
        { q: "W _ T E R (Clear liquid you drink)", a: "a" },
        { q: "E L _ P H A N T (A large animal with a trunk)", a: "e" },
        { q: "U M B R _ L L A (Keeps you dry in the rain)", a: "e" },
        { q: "H O _ S E (A place where you live)", a: "u" },
        { q: "C L _ C K (Tells the time)", a: "o" },
        { q: "P _ N C I L (Used for writing)", a: "e" },
        { q: "A N _ M A L (A living creature)", a: "i" },
        { q: "B _ R D (An animal that flies)", a: "i" },
        { q: "T R _ I N (A long vehicle on tracks)", a: "a" },
        { q: "P L _ N E (Flies in the sky)", a: "a" },
        { q: "M O N _ Y (Used to buy things)", a: "e" },
        { q: "H _ P P Y (Feeling joyful)", a: "a" },
        { q: "S _ D (Feeling unhappy)", a: "a" },
        { q: "F R _ E N D (Someone you like to play with)", a: "i" },
        { q: "B R _ T H E R (A male sibling)", a: "o" },
        { q: "S I S T _ R (A female sibling)", a: "e" },
        { q: "M O R N _ N G (Early part of the day)", a: "i" },
        { q: "E V E N _ N G (Late part of the day)", a: "i" },
        { q: "S U M M _ R (The hottest season)", a: "e" },
        { q: "W I N T _ R (The coldest season)", a: "e" },
        { q: "C H O C O L _ T E (A sweet brown treat)", a: "a" },
        { q: "I C _ (Frozen water)", a: "e" },
        { q: "F I R _ (Hot and burns)", a: "e" },
        { q: "S N _ W (White flakes from the sky)", a: "o" },
        { q: "C _ L O R (Red, blue, green are types of this)", a: "o" },
        { q: "P I C T U _ E (A drawing or photograph)", a: "r" },
        { q: "W I N D _ W (You look out of it)", a: "o" },
        { q: "D O _ R (You open it to enter a room)", a: "o" },
        { q: "T A B _ E (Furniture with four legs)", a: "l" },
        { q: "C H _ I R (Furniture you sit on)", a: "a" },
        { q: "F L O _ E R (A beautiful plant)", a: "w" },
        { q: "T R _ E (A tall plant with leaves)", a: "e" },
        { q: "G R _ S S (Green plant on the ground)", a: "a" },
        { q: "S K _ (The blue space above us)", a: "y" },
        { q: "S T _ R (Shines in the night sky)", a: "a" },
        { q: "S U _ (The hot yellow star in the day)", a: "n" },
        { q: "M O _ N (Shines at night)", a: "o" },
        { q: "B _ O K (Something you read)", a: "o" },
        { q: "P A P _ R (You write on it)", a: "e" },
        { q: "E R A S _ R (Used to rub out pencil marks)", a: "e" },
        { q: "R U L _ R (Used to measure things)", a: "e" },
        { q: "S _ O E S (Worn on your feet)", a: "h" }
    ],
    
    pastTense: [
        { q: "What is the past tense of GO?", a: "went" },
        { q: "What is the past tense of EAT?", a: "ate" },
        { q: "What is the past tense of PLAY?", a: "played" },
        { q: "What is the past tense of RUN?", a: "ran" },
        { q: "What is the past tense of JUMP?", a: "jumped" },
        { q: "What is the past tense of SLEEP?", a: "slept" },
        { q: "What is the past tense of SEE?", a: "saw" },
        { q: "What is the past tense of DRINK?", a: "drank" },
        { q: "What is the past tense of WRITE?", a: "wrote" },
        { q: "What is the past tense of READ?", a: "read" },
        { q: "What is the past tense of MAKE?", a: "made" },
        { q: "What is the past tense of BUY?", a: "bought" },
        { q: "What is the past tense of CATCH?", a: "caught" },
        { q: "What is the past tense of BRING?", a: "brought" },
        { q: "What is the past tense of THINK?", a: "thought" },
        { q: "What is the past tense of TEACH?", a: "taught" },
        { q: "What is the past tense of SPEAK?", a: "spoke" },
        { q: "What is the past tense of TAKE?", a: "took" },
        { q: "What is the past tense of GIVE?", a: "gave" },
        { q: "What is the past tense of COME?", a: "came" },
        { q: "What is the past tense of FIND?", a: "found" },
        { q: "What is the past tense of KNOW?", a: "knew" },
        { q: "What is the past tense of SAY?", a: "said" },
        { q: "What is the past tense of TELL?", a: "told" },
        { q: "What is the past tense of STAND?", a: "stood" },
        { q: "What is the past tense of SIT?", a: "sat" },
        { q: "What is the past tense of LEAVE?", a: "left" },
        { q: "What is the past tense of FEEL?", a: "felt" },
        { q: "What is the past tense of KEEP?", a: "kept" },
        { q: "What is the past tense of HEAR?", a: "heard" },
        { q: "What is the past tense of FLY?", a: "flew" },
        { q: "What is the past tense of DRIVE?", a: "drove" },
        { q: "What is the past tense of RIDE?", a: "rode" },
        { q: "What is the past tense of WEAR?", a: "wore" },
        { q: "What is the past tense of SWIM?", a: "swam" },
        { q: "What is the past tense of SING?", a: "sang" },
        { q: "What is the past tense of DRAW?", a: "drew" },
        { q: "What is the past tense of FALL?", a: "fell" },
        { q: "What is the past tense of BREAK?", a: "broke" },
        { q: "What is the past tense of CHOOSE?", a: "chose" },
        { q: "What is the past tense of WIN?", a: "won" },
        { q: "What is the past tense of LOSE?", a: "lost" },
        { q: "What is the past tense of BUILD?", a: "built" },
        { q: "What is the past tense of SEND?", a: "sent" },
        { q: "What is the past tense of SPEND?", a: "spent" },
        { q: "What is the past tense of PAY?", a: "paid" },
        { q: "What is the past tense of MEET?", a: "met" },
        { q: "What is the past tense of GROW?", a: "grew" },
        { q: "What is the past tense of THROW?", a: "threw" },
        { q: "What is the past tense of HOLD?", a: "held" }
    ],
    
    plural: [
        { q: "One cat, two ...?", a: "cats" },
        { q: "One box, two ...?", a: "boxes" },
        { q: "One child, many ...?", a: "children" },
        { q: "One dog, two ...?", a: "dogs" },
        { q: "One book, many ...?", a: "books" },
        { q: "One pen, three ...?", a: "pens" },
        { q: "One car, two ...?", a: "cars" },
        { q: "One bus, two ...?", a: "buses" },
        { q: "One fox, two ...?", a: "foxes" },
        { q: "One brush, three ...?", a: "brushes" },
        { q: "One watch, two ...?", a: "watches" },
        { q: "One glass, many ...?", a: "glasses" },
        { q: "One leaf, many ...?", a: "leaves" },
        { q: "One wolf, a pack of ...?", a: "wolves" },
        { q: "One half, two ...?", a: "halves" },
        { q: "One knife, two ...?", a: "knives" },
        { q: "One wife, two ...?", a: "wives" },
        { q: "One life, many ...?", a: "lives" },
        { q: "One thief, two ...?", a: "thieves" },
        { q: "One potato, many ...?", a: "potatoes" },
        { q: "One tomato, many ...?", a: "tomatoes" },
        { q: "One hero, two ...?", a: "heroes" },
        { q: "One city, many ...?", a: "cities" },
        { q: "One baby, two ...?", a: "babies" },
        { q: "One party, many ...?", a: "parties" },
        { q: "One story, two ...?", a: "stories" },
        { q: "One country, many ...?", a: "countries" },
        { q: "One family, many ...?", a: "families" },
        { q: "One boy, two ...?", a: "boys" },
        { q: "One toy, many ...?", a: "toys" },
        { q: "One day, seven ...?", a: "days" },
        { q: "One key, many ...?", a: "keys" },
        { q: "One monkey, two ...?", a: "monkeys" },
        { q: "One man, two ...?", a: "men" },
        { q: "One woman, many ...?", a: "women" },
        { q: "One tooth, many ...?", a: "teeth" },
        { q: "One foot, two ...?", a: "feet" },
        { q: "One goose, a flock of ...?", a: "geese" },
        { q: "One mouse, two ...?", a: "mice" },
        { q: "One person, many ...?", a: "people" },
        { q: "One sheep, a herd of ...?", a: "sheep" },
        { q: "One deer, two ...?", a: "deer" },
        { q: "One fish, a school of ...?", a: "fish" },
        { q: "One ox, two ...?", a: "oxen" },
        { q: "One bird, two ...?", a: "birds" },
        { q: "One tree, many ...?", a: "trees" },
        { q: "One flower, many ...?", a: "flowers" },
        { q: "One star, many ...?", a: "stars" },
        { q: "One cloud, many ...?", a: "clouds" },
        { q: "One shoe, a pair of ...?", a: "shoes" }
    ],
    
    spelling: [
        { q: "Fix the spelling: BEUTIFUL", a: "beautiful" },
        { q: "Fix the spelling: TOMOROW", a: "tomorrow" },
        { q: "Fix the spelling: WENSDAY", a: "wednesday" },
        { q: "Fix the spelling: RECIEVE", a: "receive" },
        { q: "Fix the spelling: ACOMDATE", a: "accommodate" },
        { q: "Fix the spelling: DEFINATELY", a: "definitely" },
        { q: "Fix the spelling: SEPERATE", a: "separate" },
        { q: "Fix the spelling: UNTILL", a: "until" },
        { q: "Fix the spelling: OCCURED", a: "occurred" },
        { q: "Fix the spelling: ALOT (one word)", a: "a lot" },
        { q: "Fix the spelling: ARGUMANT", a: "argument" },
        { q: "Fix the spelling: CALENDER", a: "calendar" },
        { q: "Fix the spelling: COLUM", a: "column" },
        { q: "Fix the spelling: EMBARASS", a: "embarrass" },
        { q: "Fix the spelling: EXISTANCE", a: "existence" },
        { q: "Fix the spelling: FORIEGN", a: "foreign" },
        { q: "Fix the spelling: FOURTY", a: "forty" },
        { q: "Fix the spelling: GOVERMENT", a: "government" },
        { q: "Fix the spelling: INDEPENDANT", a: "independent" },
        { q: "Fix the spelling: INTERUPT", a: "interrupt" },
        { q: "Fix the spelling: JELOUS", a: "jealous" },
        { q: "Fix the spelling: KNOWLEDG", a: "knowledge" },
        { q: "Fix the spelling: MISTERY", a: "mystery" },
        { q: "Fix the spelling: NECESARY", a: "necessary" },
        { q: "Fix the spelling: NOTICABLE", a: "noticeable" },
        { q: "Fix the spelling: OCASION", a: "occasion" },
        { q: "Fix the spelling: PEICE", a: "piece" },
        { q: "Fix the spelling: POSESSION", a: "possession" },
        { q: "Fix the spelling: PRIVILEDGE", a: "privilege" },
        { q: "Fix the spelling: PRONOUNCIATION", a: "pronunciation" },
        { q: "Fix the spelling: REALY", a: "really" },
        { q: "Fix the spelling: RECCOMEND", a: "recommend" },
        { q: "Fix the spelling: RYTHM", a: "rhythm" },
        { q: "Fix the spelling: SENSEBLE", a: "sensible" },
        { q: "Fix the spelling: SUCCESFUL", a: "successful" },
        { q: "Fix the spelling: SUPRISE", a: "surprise" },
        { q: "Fix the spelling: TENDANCY", a: "tendency" },
        { q: "Fix the spelling: THREFORE", a: "therefore" },
        { q: "Fix the spelling: TONG", a: "tongue" },
        { q: "Fix the spelling: TRULEY", a: "truly" },
        { q: "Fix the spelling: UNFORGETABLE", a: "unforgettable" },
        { q: "Fix the spelling: WEAKEND (Saturday & Sunday)", a: "weekend" },
        { q: "Fix the spelling: WIERD", a: "weird" },
        { q: "Fix the spelling: WRITTING", a: "writing" },
        { q: "Fix the spelling: ACHIVE", a: "achieve" },
        { q: "Fix the spelling: ADDRES", a: "address" },
        { q: "Fix the spelling: BIZNESS", a: "business" },
        { q: "Fix the spelling: ENVIROMENT", a: "environment" },
        { q: "Fix the spelling: FAMILIER", a: "familiar" },
        { q: "Fix the spelling: MINIT", a: "minute" }
    ],
    guessing: [
        { q: "I have a tail and a mane, and I like to gallop.", a: "horse" },
        { q: "I am a fruit that is usually yellow and long.", a: "banana" },
        { q: "I have four legs and I bark.", a: "dog" },
        { q: "I am the king of the jungle.", a: "lion" },
        { q: "I twinkle at night in the sky.", a: "star" },
        { q: "You use me to write on paper.", a: "pencil" },
        { q: "I have pages and stories inside me.", a: "book" },
        { q: "I am cold, white, and fall from the sky in winter.", a: "snow" },
        { q: "I have a long neck to eat leaves from tall trees.", a: "giraffe" },
        { q: "I am the round object that shines during the day.", a: "sun" },
        { q: "I have many teeth but cannot bite. I fix your hair.", a: "comb" },
        { q: "You wear me on your feet to go running.", a: "shoes" },
        { q: "I am a place where you go to learn.", a: "school" },
        { q: "I am a bird that can swim but cannot fly. I live in the cold.", a: "penguin" },
        { q: "I help you stay dry when it rains.", a: "umbrella" },
        { q: "I am a large animal with a very long trunk.", a: "elephant" },
        { q: "You use me to cut paper.", a: "scissors" },
        { q: "I am a red fruit with seeds on the outside.", a: "strawberry" },
        { q: "I am the person who treats sick people.", a: "doctor" },
        { q: "I am a room where you cook food.", a: "kitchen" },
        { q: "I have wings but I am not a bird. I carry passengers.", a: "airplane" },
        { q: "I am a slow animal with a hard shell.", a: "turtle" },
        { q: "I am what you use to smell things.", a: "nose" },
        { q: "I am the opposite of day.", a: "night" },
        { q: "I am a giant cat with stripes.", a: "tiger" },
        { q: "I am a place where you can see many wild animals.", a: "zoo" },
        { q: "I grow on your head and can be cut.", a: "hair" },
        { q: "I am a insect that makes honey.", a: "bee" },
        { q: "I am a sweet treat that melts in the sun.", a: "icecream" },
        { q: "I am a building where you watch movies.", a: "cinema" },
        { q: "I am the color of the grass.", a: "green" },
        { q: "I am a machine that tells the time.", a: "clock" },
        { q: "I have a screen and a keyboard.", a: "computer" },
        { q: "I am a person who flies a plane.", a: "pilot" },
        { q: "I am a sport played with a round ball and feet.", a: "football" },
        { q: "I am the planet we live on.", a: "earth" },
        { q: "I am a month that starts with 'J' and has 31 days.", a: "january" },
        { q: "I am a shape with three sides.", a: "triangle" },
        { q: "I am the son of your father and mother.", a: "brother" },
        { q: "I am a vehicle with two wheels and no engine.", a: "bicycle" },
        { q: "I am the liquid inside a pen.", a: "ink" },
        { q: "I am the largest ocean in the world.", a: "pacific" },
        { q: "I am a piece of furniture you sleep on.", a: "bed" },
        { q: "I am the sound a cat makes.", a: "meow" },
        { q: "I am a yellow flower that follows the sun.", a: "sunflower" },
        { q: "I am a large body of salt water.", a: "ocean" },
        { q: "I am the tool you use to eat soup.", a: "spoon" },
        { q: "I am a colorful arc in the sky after rain.", a: "rainbow" },
        { q: "I am the holiday celebrated on December 25th.", a: "christmas" },
        { q: "I am the capital city of Malaysia.", a: "kuala lumpur" }
    ],
    puzzle: [
        { q: "C-H-E-A-T-R-E", a: "teacher" }, { q: "D-N-I-E-F-R", a: "friend" },
        { q: "N-D-A-G-R-E", a: "garden" }, { q: "D-O-W-W-I-N", a: "window" },
        { q: "L-Y-M-A-I-F", a: "family" }, { q: "G-N-E-R-O-A", a: "orange" },
        { q: "R-E-T-M-O-H", a: "mother" }, { q: "R-A-H-T-F-E", a: "father" },
        { q: "T-I-C-S-P-A-L", a: "plastic" }, { q: "T-E-L-T-O-B", a: "bottle" },
        { q: "K-E-R-M-A-T", a: "market" }, { q: "L-I-C-E-N-P", a: "pencil" },
        { q: "R-U-M-S-M-E", a: "summer" }, { q: "T-E-N-I-R-W", a: "winter" },
        { q: "F-E-E-O-C-F", a: "coffee" }, { q: "R-E-N-N-I-D", a: "dinner" },
        { q: "W-O-L-E-Y-L", a: "yellow" }, { q: "E-D-G-R-I-B", a: "bridge" },
        { q: "K-E-N-I-C-C-H", a: "chicken" }, { q: "N-I-P-L-O-H-D", a: "dolphin" },
        { q: "R-G-E-U-M-A-H-R-B", a: "hamburger" }, { q: "N-I-A-T-O-U-M-N", a: "mountain" },
        { q: "L-A-T-P-I-O-S-H", a: "hospital" }, { q: "Y-A-D-H-T-R-I-B", a: "birthday" },
        { q: "T-N-A-H-E-P-E-L", a: "elephant" }, { q: "R-E-T-U-P-O-M-C", a: "computer" },
        { q: "N-E-H-C-T-I-K", a: "kitchen" }, { q: "H-C-I-W-D-N-A-S", a: "sandwich" },
        { q: "E-L-B-A-T-E-G-E-V", a: "vegetable" }, { q: "E-S-R-E-V-I-N-U", a: "universe" },
        { q: "Y-R-A-R-B-I-L", a: "library" }, { q: "N-I-A-T-P-A-C", a: "captain" },
        { q: "Y-A-D-I-L-O-H", a: "holiday" }, { q: "Y-L-F-R-E-T-T-U-B", a: "butterfly" },
        { q: "D-N-O-M-A-I-D", a: "diamond" }, { q: "L-A-V-I-T-S-E-F", a: "festival" },
        { q: "E-N-I-Z-A-G-A-M", a: "magazine" }, { q: "R-U-O-B-H-G-I-E-N", a: "neighbour" },
        { q: "N-O-I-T-S-E-U-Q", a: "question" }, { q: "Y-R-R-E-B-W-A-R-T-S", a: "strawberry" },
        { q: "E-L-G-N-A-I-R-T", a: "triangle" }, { q: "E-G-A-L-L-I-V", a: "village" },
        { q: "R-E-H-T-A-E-W", a: "weather" }, { q: "Y-A-D-R-E-T-S-E-Y", a: "yesterday" },
        { q: "A-R-B-E-Z", a: "zebra" }, { q: "L-A-M-I-N-A", a: "animal" },
        { q: "L-U-F-I-T-U-A-E-B", a: "beautiful" }, { q: "Y-R-T-N-U-O-C", a: "country" },
        { q: "S-U-O-R-E-G-N-A-D", a: "dangerous" }, { q: "E-S-I-C-R-E-X-E", a: "exercise" }
    ],
    synonym: [
        { q: "Synonym of 'Happy'", a: "joyful|glad|cheerful" },
        { q: "Synonym of 'Big'", a: "huge|large|giant" },
        { q: "Synonym of 'Fast'", a: "quick|rapid|speedy" },
        { q: "Synonym of 'Smart'", a: "intelligent|clever|bright" },
        { q: "Synonym of 'Small'", a: "tiny|little|mini" },
        { q: "Synonym of 'Beautiful'", a: "pretty|lovely|gorgeous" },
        { q: "Synonym of 'Quiet'", a: "silent|calm|peaceful" },
        { q: "Synonym of 'Simple'", a: "easy|basic|plain" },
        { q: "Synonym of 'Sick'", a: "ill|unwell" },
        { q: "Synonym of 'Angry'", a: "mad|furious" },
        { q: "Synonym of 'Gift'", a: "present|reward" },
        { q: "Synonym of 'Begin'", a: "start|commence" },
        { q: "Synonym of 'Sad'", a: "unhappy|sorrowful|depressed" },
        { q: "Synonym of 'Funny'", a: "hilarious|comical|amusing" },
        { q: "Synonym of 'Shout'", a: "yell|scream|cry" },
        { q: "Synonym of 'Scared'", a: "afraid|frightened|terrified" },
        { q: "Synonym of 'Rich'", a: "wealthy|affluent" },
        { q: "Synonym of 'Buy'", a: "purchase|get" },
        { q: "Synonym of 'Finish'", a: "end|complete|conclude" },
        { q: "Synonym of 'Help'", a: "assist|support|aid" },
        { q: "Synonym of 'Idea'", a: "thought|concept|plan" },
        { q: "Synonym of 'Job'", a: "work|occupation|career" },
        { q: "Synonym of 'Look'", a: "see|watch|stare" },
        { q: "Synonym of 'Make'", a: "create|build|produce" },
        { q: "Synonym of 'Neat'", a: "tidy|clean|orderly" },
        { q: "Synonym of 'Old'", a: "ancient|aged" },
        { q: "Synonym of 'Part'", a: "section|piece|portion" },
        { q: "Synonym of 'Right'", a: "correct|accurate|true" },
        { q: "Synonym of 'Safe'", a: "secure|protected" },
        { q: "Synonym of 'Tell'", a: "say|speak|inform" },
        { q: "Synonym of 'Use'", a: "utilize|employ" },
        { q: "Synonym of 'Wrong'", a: "incorrect|false|mistaken" },
        { q: "Synonym of 'Always'", a: "forever|constantly" },
        { q: "Synonym of 'Brave'", a: "courageous|fearless|bold" },
        { q: "Synonym of 'Cold'", a: "chilly|freezing|cool" },
        { q: "Synonym of 'Dirty'", a: "messy|unclean|filthy" },
        { q: "Synonym of 'Enjoy'", a: "like|love|appreciate" },
        { q: "Synonym of 'Famous'", a: "well-known|popular|renowned" },
        { q: "Synonym of 'Good'", a: "great|excellent|fine" },
        { q: "Synonym of 'Hard'", a: "difficult|tough|solid" },
        { q: "Synonym of 'Important'", a: "crucial|significant|vital" },
        { q: "Synonym of 'Jump'", a: "leap|hop|bounce" },
        { q: "Synonym of 'Keep'", a: "hold|save|retain" },
        { q: "Synonym of 'Lazy'", a: "idle|sluggish|inactive" },
        { q: "Synonym of 'Many'", a: "numerous|multiple|plenty" },
        { q: "Synonym of 'New'", a: "fresh|modern|recent" },
        { q: "Synonym of 'Polite'", a: "courteous|respectful|civil" },
        { q: "Synonym of 'Strong'", a: "powerful|tough|sturdy" },
        { q: "Synonym of 'Tired'", a: "sleepy|exhausted|fatigued" },
        { q: "Synonym of 'Weak'", a: "frail|fragile|feeble" }
    ],
    antonym: [
        { q: "Antonym of 'Hot'", a: "cold|freezing" },
        { q: "Antonym of 'Up'", a: "down" },
        { q: "Antonym of 'Good'", a: "bad|evil|terrible" },
        { q: "Antonym of 'Fast'", a: "slow" },
        { q: "Antonym of 'Happy'", a: "sad|unhappy|depressed" },
        { q: "Antonym of 'Big'", a: "small|tiny|little" },
        { q: "Antonym of 'Light'", a: "dark|heavy" },
        { q: "Antonym of 'Day'", a: "night" },
        { q: "Antonym of 'Open'", a: "close|closed|shut" },
        { q: "Antonym of 'New'", a: "old|ancient" },
        { q: "Antonym of 'Rich'", a: "poor|broke" },
        { q: "Antonym of 'Hard'", a: "soft|easy" },
        { q: "Antonym of 'Empty'", a: "full" },
        { q: "Antonym of 'Clean'", a: "dirty|messy" },
        { q: "Antonym of 'Strong'", a: "weak|frail" },
        { q: "Antonym of 'Right'", a: "wrong|left" },
        { q: "Antonym of 'Tall'", a: "short" },
        { q: "Antonym of 'Beautiful'", a: "ugly" },
        { q: "Antonym of 'Brave'", a: "coward|scared|fearful" },
        { q: "Antonym of 'Cheap'", a: "expensive|costly" },
        { q: "Antonym of 'Cry'", a: "laugh|smile" },
        { q: "Antonym of 'Early'", a: "late" },
        { q: "Antonym of 'Fat'", a: "thin|skinny|slim" },
        { q: "Antonym of 'First'", a: "last|final" },
        { q: "Antonym of 'Friend'", a: "enemy|foe" },
        { q: "Antonym of 'Give'", a: "take|receive" },
        { q: "Antonym of 'Inside'", a: "outside" },
        { q: "Antonym of 'Loud'", a: "quiet|silent|soft" },
        { q: "Antonym of 'Love'", a: "hate|dislike" },
        { q: "Antonym of 'Near'", a: "far|distant" },
        { q: "Antonym of 'Never'", a: "always|forever" },
        { q: "Antonym of 'Pull'", a: "push" },
        { q: "Antonym of 'Rough'", a: "smooth|soft" },
        { q: "Antonym of 'Safe'", a: "dangerous|unsafe" },
        { q: "Antonym of 'Same'", a: "different|opposite" },
        { q: "Antonym of 'Start'", a: "stop|finish|end" },
        { q: "Antonym of 'Sweet'", a: "sour|bitter" },
        { q: "Antonym of 'Thick'", a: "thin" },
        { q: "Antonym of 'True'", a: "false|fake" },
        { q: "Antonym of 'Win'", a: "lose" },
        { q: "Antonym of 'Young'", a: "old" },
        { q: "Antonym of 'Alive'", a: "dead" },
        { q: "Antonym of 'Awake'", a: "asleep|sleeping" },
        { q: "Antonym of 'Careful'", a: "careless|reckless" },
        { q: "Antonym of 'Cruel'", a: "kind|gentle|compassionate" },
        { q: "Antonym of 'Deep'", a: "shallow" },
        { q: "Antonym of 'Float'", a: "sink" },
        { q: "Antonym of 'Generous'", a: "stingy|selfish|greedy" },
        { q: "Antonym of 'Healthy'", a: "sick|ill|unhealthy" },
        { q: "Antonym of 'Import'", a: "export" }
    ]
};

// ==========================================
// 2. DATA AVATAR / GUARDIANS (10 JENIS & 10 LEVEL)
// ==========================================
const avatars = {
    dragon: {
        id: 'avatar_dragon', maxLevel: 10, theme: 'Grammar & Syntax',
        levels: [
            { level: 1, name: 'Noun Egg', price: 300, icon: 'fas fa-egg fa-pulse text-orange-200', desc: 'A basic naming word waiting to hatch.' },
            { level: 2, name: 'Verb Hatchling', price: 300, icon: 'fas fa-egg fa-shake text-orange-300', desc: 'It is moving! An action word is born.' },
            { level: 3, name: 'Adjective Drake', price: 300, icon: 'fas fa-dragon fa-bounce text-orange-400', desc: 'Adding colorful descriptions to sentences.' },
            { level: 4, name: 'Pronoun Flyer', price: 300, icon: 'fas fa-dragon fa-fade text-orange-500', desc: 'Replacing nouns and flying higher.' },
            { level: 5, name: 'Adverb Dragon', price: 300, icon: 'fas fa-dragon fa-beat text-red-400', desc: 'Modifying actions with incredible speed.' },
            { level: 6, name: 'Conjunction Beast', price: 300, icon: 'fas fa-dragon fa-shake text-red-500', desc: 'Connecting clauses and strong ideas.' },
            { level: 7, name: 'Syntax Commander', price: 300, icon: 'fas fa-dragon fa-bounce text-red-600', desc: 'Mastering the order of words.' },
            { level: 8, name: 'Sentence Ancient', price: 300, icon: 'fas fa-fire-alt fa-beat text-red-700', desc: 'Crafting complex and flawless sentences.' },
            { level: 9, name: 'Grammar Mythic', price: 300, icon: 'fas fa-fire-alt fa-pulse text-red-800', desc: 'The ultimate guardian of language rules.' },
            { 
                level: 10, 
                name: 'Supreme Grammarian', 
                price: 300, 
                img: 'avatar_dragon.png', 
                icon: 'fas fa-dragon fa-beat legendary-avatar text-red-600 drop-shadow-lg text-2xl', 
                desc: 'The God of Grammar! Unstoppable accuracy!' 
            }
        ]
    },
    owl: {
        id: 'avatar_owl', maxLevel: 10, theme: 'Vocabulary & Spelling',
        levels: [
            { level: 1, name: 'Phonics Egg', price: 300, icon: 'fas fa-egg fa-pulse text-blue-200', desc: 'The foundation of sounds and letters.' },
            { level: 2, name: 'Syllable Egg', price: 300, icon: 'fas fa-egg fa-shake text-blue-300', desc: 'Vibrating with word parts.' },
            { level: 3, name: 'Vocab Owlet', price: 300, icon: 'fas fa-crow fa-bounce text-blue-400', desc: 'Learning its first new words.' },
            { level: 4, name: 'Spelling Owl', price: 300, icon: 'fas fa-crow fa-fade text-blue-500', desc: 'Never makes a typo.' },
            { level: 5, name: 'Lexicon Reader', price: 300, icon: 'fas fa-crow fa-beat text-indigo-400', desc: 'Expanding its personal dictionary.' },
            { level: 6, name: 'Synonym Master', price: 300, icon: 'fas fa-feather fa-shake text-indigo-500', desc: 'Always knows another word for it.' },
            { level: 7, name: 'Antonym Guardian', price: 300, icon: 'fas fa-feather fa-bounce text-indigo-600', desc: 'Master of opposites and contrasts.' },
            { level: 8, name: 'Thesaurus Ancient', price: 300, icon: 'fas fa-feather-alt fa-beat text-indigo-700', desc: 'Holds thousands of brilliant words.' },
            { level: 9, name: 'Etymology Mythic', price: 300, icon: 'fas fa-feather-alt fa-pulse text-indigo-800', desc: 'Knows the true origin of all languages.' },
            { 
                level: 10, 
                name: 'Supreme Wordsmith', 
                price: 300, 
                img: 'avatar_owl.png',
                icon: 'fas fa-feather-alt fa-beat legendary-avatar text-indigo-500 drop-shadow-lg text-2xl', 
                desc: 'The Guardian of the Ultimate Dictionary!' 
            }
        ]
    },
    bot: {
        id: 'avatar_bot', maxLevel: 10, theme: 'Punctuation & Mechanics',
        levels: [
            { level: 1, name: 'Comma Cube', price: 300, icon: 'fas fa-box fa-pulse text-gray-300', desc: 'A basic pause in the sentence.' },
            { level: 2, name: 'Period Processor', price: 300, icon: 'fas fa-box fa-shake text-gray-400', desc: 'Ending sentences with certainty.' },
            { level: 3, name: 'Hyphen Bot', price: 300, icon: 'fas fa-microchip fa-bounce text-teal-300', desc: 'Connecting compound words.' },
            { level: 4, name: 'Apostrophe Mecha', price: 300, icon: 'fas fa-robot fa-fade text-teal-400', desc: 'Showing ownership and contractions.' },
            { level: 5, name: 'Quotation Bot', price: 300, icon: 'fas fa-robot fa-beat text-teal-500', desc: 'Capturing exact dialogue safely.' },
            { level: 6, name: 'Colon Cyborg', price: 300, icon: 'fas fa-robot fa-shake text-teal-600', desc: 'Introducing lists and explanations.' },
            { level: 7, name: 'Semicolon Armor', price: 300, icon: 'fas fa-robot fa-bounce text-blue-500', desc: 'Linking independent clauses like a pro.' },
            { level: 8, name: 'Exclamation Ancient', price: 300, icon: 'fas fa-user-astronaut fa-beat text-blue-600', desc: 'Expressing strong emotions!' },
            { level: 9, name: 'Mechanics Mythic', price: 300, icon: 'fas fa-user-astronaut fa-pulse text-purple-600', desc: 'Scanning text for perfect formatting.' },
            { 
                level: 10, 
                name: 'Supreme Editor', 
                price: 300, 
                img: 'avatar_bot.png',
                icon: 'fas fa-user-astronaut fa-spin legendary-avatar text-purple-500 drop-shadow-lg text-2xl', 
                desc: 'The Flawless Proofreading Titan!' 
            }
        ]
    },
    wolf: {
        id: 'avatar_wolf', maxLevel: 10, theme: 'Speaking & Fluency',
        levels: [
            { level: 1, name: 'Whisper Paw', price: 300, icon: 'fas fa-paw fa-pulse text-cyan-200', desc: 'Practicing quiet pronunciation.' },
            { level: 2, name: 'Echo Paw', price: 300, icon: 'fas fa-paw fa-shake text-cyan-300', desc: 'Repeating native sounds perfectly.' },
            { level: 3, name: 'Vocal Pup', price: 300, icon: 'fas fa-dog fa-bounce text-cyan-400', desc: 'Speaking short phrases with joy.' },
            { level: 4, name: 'Chatter Wolf', price: 300, icon: 'fas fa-dog fa-fade text-cyan-500', desc: 'Engaging in small talk.' },
            { level: 5, name: 'Dialogue Hunter', price: 300, icon: 'fas fa-dog fa-beat text-blue-400', desc: 'Mastering conversational English.' },
            { level: 6, name: 'Fluency Alpha', price: 300, icon: 'fas fa-dog fa-shake text-blue-500', desc: 'Speaking smoothly without hesitation.' },
            { level: 7, name: 'Accent Master', price: 300, icon: 'fas fa-dog fa-bounce text-blue-600', desc: 'Adapting to different English intonations.' },
            { level: 8, name: 'Articulation Ancient', price: 300, icon: 'fas fa-moon fa-beat text-blue-700', desc: 'Clear and powerful speech delivery.' },
            { level: 9, name: 'Eloquence Mythic', price: 300, icon: 'fas fa-moon fa-pulse text-blue-800', desc: 'Persuading the pack with words.' },
            { 
                level: 10, 
                name: 'Supreme Orator', 
                price: 300, 
                img: 'avatar_wolf.png',
                icon: 'fas fa-moon fa-beat legendary-avatar text-cyan-500 drop-shadow-lg text-2xl', 
                desc: 'The Legendary Voice of the Forest!' 
            }
        ]
    },
    phoenix: {
        id: 'avatar_phoenix', maxLevel: 10, theme: 'Writing & Composition',
        levels: [
            { level: 1, name: 'Idea Feather', price: 300, icon: 'fas fa-fire fa-pulse text-yellow-300', desc: 'A tiny spark of a writing topic.' },
            { level: 2, name: 'Drafting Feather', price: 300, icon: 'fas fa-fire fa-shake text-yellow-400', desc: 'Putting first thoughts on paper.' },
            { level: 3, name: 'Outline Chick', price: 300, icon: 'fas fa-dove fa-bounce text-orange-300', desc: 'Organizing the essay structure.' },
            { level: 4, name: 'Paragraph Bird', price: 300, icon: 'fas fa-dove fa-fade text-orange-400', desc: 'Writing strong topic sentences.' },
            { level: 5, name: 'Essay Flier', price: 300, icon: 'fas fa-dove fa-beat text-orange-500', desc: 'Connecting paragraphs with transitions.' },
            { level: 6, name: 'Revision Bird', price: 300, icon: 'fas fa-dove fa-shake text-red-400', desc: 'Improving and rewriting better drafts.' },
            { level: 7, name: 'Article Master', price: 300, icon: 'fas fa-dove fa-bounce text-red-500', desc: 'Publishing captivating articles.' },
            { level: 8, name: 'Manuscript Ancient', price: 300, icon: 'fas fa-fire-alt fa-beat text-red-600', desc: 'A legend in creative writing.' },
            { level: 9, name: 'Bestseller Mythic', price: 300, icon: 'fas fa-fire-alt fa-pulse text-red-700', desc: 'Words that live forever.' },
            { 
                level: 10, 
                name: 'Supreme Author', 
                price: 300, 
                img: 'avatar_phoenix.png',
                icon: 'fas fa-fire-alt fa-beat legendary-avatar text-yellow-500 drop-shadow-lg text-2xl', 
                desc: 'The Immortal Master of Stories!' 
            }
        ]
    },
    leviathan: {
        id: 'avatar_leviathan', maxLevel: 10, theme: 'Reading & Comprehension',
        levels: [
            { level: 1, name: 'Context Drop', price: 300, icon: 'fas fa-tint fa-pulse text-blue-200', desc: 'Guessing meaning from context.' },
            { level: 2, name: 'Skimming Drop', price: 300, icon: 'fas fa-tint fa-shake text-blue-300', desc: 'Reading fast to get the main idea.' },
            { level: 3, name: 'Scanning Fish', price: 300, icon: 'fas fa-fish fa-bounce text-teal-300', desc: 'Looking closely for specific facts.' },
            { level: 4, name: 'Inference Spirit', price: 300, icon: 'fas fa-fish fa-fade text-teal-400', desc: 'Reading between the lines.' },
            { level: 5, name: 'Summary Swimmer', price: 300, icon: 'fas fa-fish fa-beat text-teal-500', desc: 'Condensing long texts easily.' },
            { level: 6, name: 'Analysis Spirit', price: 300, icon: 'fas fa-fish fa-shake text-teal-600', desc: 'Breaking down complex paragraphs.' },
            { level: 7, name: 'Comprehension Master', price: 300, icon: 'fas fa-water fa-bounce text-blue-500', desc: 'Understanding the deepest texts.' },
            { level: 8, name: 'Literature Ancient', price: 300, icon: 'fas fa-water fa-beat text-blue-600', desc: 'Devouring classic novels.' },
            { level: 9, name: 'Epic Mythic', price: 300, icon: 'fas fa-water fa-pulse text-blue-700', desc: 'Mastering poetry and prose.' },
            { 
                level: 10, 
                name: 'Supreme Scholar', 
                price: 300, 
                img: 'avatar_leviathan.png',
                icon: 'fas fa-water fa-beat legendary-avatar text-blue-500 drop-shadow-lg text-2xl', 
                desc: 'An unstoppable wave of knowledge!' 
            }
        ]
    },
    unicorn: {
        id: 'avatar_unicorn', maxLevel: 10, theme: 'Figurative Language',
        levels: [
            { level: 1, name: 'Rhyme Dust', price: 300, icon: 'fas fa-star fa-pulse text-pink-200', desc: 'Words that sound magically alike.' },
            { level: 2, name: 'Simile Dust', price: 300, icon: 'fas fa-star fa-shake text-pink-300', desc: 'As bright as a glowing star.' },
            { level: 3, name: 'Metaphor Pony', price: 300, icon: 'fas fa-horse fa-bounce text-pink-400', desc: 'A pony that IS a star.' },
            { level: 4, name: 'Personification Pony', price: 300, icon: 'fas fa-horse fa-fade text-pink-500', desc: 'Making non-human things alive.' },
            { level: 5, name: 'Idiom Mystic', price: 300, icon: 'fas fa-horse fa-beat text-purple-400', desc: 'Raining cats and dogs!' },
            { level: 6, name: 'Hyperbole Unicorn', price: 300, icon: 'fas fa-horse fa-shake text-purple-500', desc: 'The fastest creature in a million years.' },
            { level: 7, name: 'Alliteration Master', price: 300, icon: 'fas fa-horse-head fa-bounce text-purple-600', desc: 'Creating cool consonant combos.' },
            { level: 8, name: 'Poetic Ancient', price: 300, icon: 'fas fa-horse-head fa-beat text-purple-700', desc: 'Master of verses and stanzas.' },
            { level: 9, name: 'Inspiration Mythic', price: 300, icon: 'fas fa-horse-head fa-pulse text-pink-600', desc: 'Sparking creative writing ideas.' },
            { 
                level: 10, 
                name: 'Supreme Bard', 
                price: 300, 
                img: 'avatar_unicorn.png',
                icon: 'fas fa-horse-head fa-beat legendary-avatar text-pink-500 drop-shadow-lg text-2xl', 
                desc: 'The most beautiful magic in literature!' 
            }
        ]
    },
    golem: {
        id: 'avatar_golem', maxLevel: 10, theme: 'Tenses & Structure',
        levels: [
            { level: 1, name: 'Past Pebble', price: 300, icon: 'fas fa-circle fa-pulse text-gray-400', desc: 'Actions that already happened.' },
            { level: 2, name: 'Present Pebble', price: 300, icon: 'fas fa-circle fa-shake text-gray-500', desc: 'Actions happening right now.' },
            { level: 3, name: 'Future Rock', price: 300, icon: 'fas fa-cube fa-bounce text-gray-600', desc: 'Plans that will happen tomorrow.' },
            { level: 4, name: 'Continuous Stone', price: 300, icon: 'fas fa-cube fa-fade text-gray-700', desc: 'Rolling with the -ing verbs.' },
            { level: 5, name: 'Perfect Tense Guardian', price: 300, icon: 'fas fa-cubes fa-beat text-gray-800', desc: 'Has mastered the past participles.' },
            { level: 6, name: 'Active Voice Iron', price: 300, icon: 'fas fa-cubes fa-shake text-gray-900', desc: 'Direct, clear, and unbreakable.' },
            { level: 7, name: 'Passive Voice Golem', price: 300, icon: 'fas fa-mountain fa-bounce text-gray-600', desc: 'Actions are being done to it.' },
            { level: 8, name: 'Conditional Ancient', price: 300, icon: 'fas fa-mountain fa-beat text-gray-700', desc: 'If you study, you will succeed.' },
            { level: 9, name: 'Structure Mythic', price: 300, icon: 'fas fa-mountain fa-pulse text-gray-800', desc: 'A walking mountain of solid grammar.' },
            { 
                level: 10, 
                name: 'Supreme Foundation', 
                price: 300, 
                img: 'avatar_golem.png',
                icon: 'fas fa-mountain fa-shake legendary-avatar text-gray-900 drop-shadow-lg text-2xl', 
                desc: 'The Unshakeable Earth Shaker!' 
            }
        ]
    },
    fairy: {
        id: 'avatar_fairy', maxLevel: 10, theme: 'Listening & Communication',
        levels: [
            { level: 1, name: 'Sound Seedling', price: 300, icon: 'fas fa-seedling fa-pulse text-green-300', desc: 'Catching the first English sounds.' },
            { level: 2, name: 'Tune Sprout', price: 300, icon: 'fas fa-seedling fa-shake text-green-400', desc: 'Listening to the rhythm of sentences.' },
            { level: 3, name: 'Audio Sprite', price: 300, icon: 'fas fa-leaf fa-bounce text-green-500', desc: 'Understanding short instructions.' },
            { level: 4, name: 'Podcast Sprite', price: 300, icon: 'fas fa-leaf fa-fade text-green-600', desc: 'Enjoying English stories in the wind.' },
            { level: 5, name: 'Conversation Fairy', price: 300, icon: 'fas fa-tree fa-beat text-green-700', desc: 'Planting ideas through dialogue.' },
            { level: 6, name: 'Active Listener', price: 300, icon: 'fas fa-tree fa-shake text-green-800', desc: 'Paying close attention to details.' },
            { level: 7, name: 'Nuance Master', price: 300, icon: 'fas fa-tree fa-bounce text-teal-600', desc: 'Understanding tone and emotion.' },
            { level: 8, name: 'Interpreter Ancient', price: 300, icon: 'fas fa-tree fa-beat text-teal-700', desc: 'Translating thoughts seamlessly.' },
            { level: 9, name: 'Polyglot Mythic', price: 300, icon: 'fas fa-tree fa-pulse text-teal-800', desc: 'Glowing with communication magic.' },
            { 
                level: 10, 
                name: 'Supreme Communicator', 
                price: 300, 
                img: 'avatar_fairy.png',
                icon: 'fas fa-tree fa-beat legendary-avatar text-green-500 drop-shadow-lg text-2xl', 
                desc: 'The Queen of Global Connections!' 
            }
        ]
    },
    lion: {
        id: 'avatar_lion', maxLevel: 10, theme: 'Debate & Persuasion',
        levels: [
            { level: 1, name: 'Claim Kitten', price: 300, icon: 'fas fa-bolt fa-pulse text-yellow-200', desc: 'Making a tiny but valid point.' },
            { level: 2, name: 'Reason Kitten', price: 300, icon: 'fas fa-bolt fa-shake text-yellow-300', desc: 'Backing up claims with "because".' },
            { level: 3, name: 'Logic Cub', price: 300, icon: 'fas fa-cat fa-bounce text-yellow-400', desc: 'Thinking fast and making sense.' },
            { level: 4, name: 'Evidence Volt Cat', price: 300, icon: 'fas fa-cat fa-fade text-yellow-500', desc: 'Running with facts and statistics.' },
            { level: 5, name: 'Argument Cat', price: 300, icon: 'fas fa-cat fa-beat text-orange-400', desc: 'Building strong, shocking cases.' },
            { level: 6, name: 'Rebuttal Lion', price: 300, icon: 'fas fa-cat fa-shake text-orange-500', desc: 'Countering opposing views with thunder.' },
            { level: 7, name: 'Persuasion Master', price: 300, icon: 'fas fa-crown fa-bounce text-yellow-500', desc: 'Convincing the crowd easily.' },
            { level: 8, name: 'Rhetoric Ancient', price: 300, icon: 'fas fa-crown fa-beat text-yellow-600', desc: 'A legendary speaker of the sky.' },
            { level: 9, name: 'Debate Mythic', price: 300, icon: 'fas fa-crown fa-pulse text-orange-600', desc: 'Summoning lightning-fast responses.' },
            { 
                level: 10, 
                name: 'Supreme Statesman', 
                price: 300, 
                img: 'avatar_lion.png',
                icon: 'fas fa-crown fa-beat legendary-avatar text-yellow-400 drop-shadow-lg text-2xl', 
                desc: 'The Absolute King of the Stage!' 
            }
        ]
    }
};
// ==========================================
// 3. DATA ITEM KEDAI (BADGE & EDU ITEMS)
// ==========================================
const shopItems = [
    // ------------------------------------------
    // KATEGORI: GRAMMAR BADGES
    // ------------------------------------------
    { id: 'badge_grammar_1', category: 'badge', name: 'Beginner Grammar', price: 300, icon: 'fas fa-star text-green-300', desc: 'A good start for your grammar journey!' },
    { id: 'badge_grammar_2', category: 'badge', name: 'Novice Grammar', price: 400, icon: 'fas fa-medal text-green-400', desc: 'You are getting better at grammar.' },
    { id: 'badge_grammar_3', category: 'badge', name: 'Intermediate Grammar', price: 500, icon: 'fas fa-rosette text-green-500', desc: 'Solid grammar skills proven.' },
    { id: 'badge_grammar_4', category: 'badge', name: 'Advanced Grammar', price: 600, icon: 'fas fa-certificate text-green-600', desc: 'Excellent understanding of grammar.' },
    { id: 'badge_grammar_5', category: 'badge', name: 'Master Grammar', price: 700, icon: 'fas fa-award text-green-700', desc: 'A shiny badge to show off perfect grammar!' },
    { id: 'badge_grammar_6', category: 'badge', name: 'Ultimate Grammar', price: 800, icon: 'fas fa-trophy text-green-800', desc: 'The God of Grammar! Flawless!' },

    // ------------------------------------------
    // KATEGORI: VOCABULARY BADGES
    // ------------------------------------------
    { id: 'badge_vocab_1', category: 'badge', name: 'Beginner Vocab', price: 300, icon: 'fas fa-star text-purple-300', desc: 'Learning new words every day.' },
    { id: 'badge_vocab_2', category: 'badge', name: 'Novice Vocab', price: 400, icon: 'fas fa-medal text-purple-400', desc: 'Your vocabulary is expanding.' },
    { id: 'badge_vocab_3', category: 'badge', name: 'Intermediate Vocab', price: 500, icon: 'fas fa-rosette text-purple-500', desc: 'You know a lot of useful words.' },
    { id: 'badge_vocab_4', category: 'badge', name: 'Advanced Vocab', price: 600, icon: 'fas fa-certificate text-purple-600', desc: 'A walking dictionary!' },
    { id: 'badge_vocab_5', category: 'badge', name: 'Vocab Master', price: 700, icon: 'fas fa-award text-purple-700', desc: 'Proof that you know thousands of words.' },
    { id: 'badge_vocab_6', category: 'badge', name: 'Ultimate Vocab King', price: 800, icon: 'fas fa-crown text-purple-800', desc: 'The ruler of all English words!' },

    // ------------------------------------------
    // KATEGORI: SPEED RUNNER BADGES
    // ------------------------------------------
    { id: 'badge_speed_1', category: 'badge', name: 'Beginner Speed', price: 300, icon: 'fas fa-star text-blue-300', desc: 'Answering questions at a steady pace.' },
    { id: 'badge_speed_2', category: 'badge', name: 'Novice Speed', price: 400, icon: 'fas fa-medal text-blue-400', desc: 'Getting faster with your fingers.' },
    { id: 'badge_speed_3', category: 'badge', name: 'Intermediate Speed', price: 500, icon: 'fas fa-rosette text-blue-500', desc: 'Quick thinker and fast typer.' },
    { id: 'badge_speed_4', category: 'badge', name: 'Advanced Speed', price: 600, icon: 'fas fa-certificate text-blue-600', desc: 'Lightning fast reflexes!' },
    { id: 'badge_speed_5', category: 'badge', name: 'Speed Master', price: 700, icon: 'fas fa-award text-blue-700', desc: 'Almost impossible to beat your speed.' },
    { id: 'badge_speed_6', category: 'badge', name: 'Ultimate Speedster', price: 800, icon: 'fas fa-bolt text-blue-800', desc: 'The speed of light! Unstoppable!' },

// ------------------------------------------
    // KATEGORI: EDU SHOP (BARANGAN SEKOLAH / ALAT TULIS)
    // ------------------------------------------
    { id: 'edu_eraser', category: 'edu', name: 'Eraser', price: 100, icon: 'fas fa-eraser text-pink-400', desc: 'A basic pink eraser to fix tiny mistakes.' },
    { id: 'edu_pencil', category: 'edu', name: 'Pencil', price: 150, icon: 'fas fa-pencil-alt text-yellow-500', desc: 'A sharp 2B pencil for writing down answers.' },
    { id: 'edu_pen', category: 'edu', name: 'Pen', price: 200, icon: 'fas fa-pen text-blue-600', desc: 'A smooth blue pen for confident writing.' },
    { id: 'edu_ruler', category: 'edu', name: 'Ruler', price: 250, icon: 'fas fa-ruler text-green-500', desc: 'Keep your lines straight and neat.' },
    { id: 'edu_sharpener', category: 'edu', name: 'Sharpener', price: 300, icon: 'fas fa-cube text-red-500', desc: 'Keep your pencils sharp and ready.' },
    { id: 'edu_exercise_book', category: 'edu', name: 'Exercise Book', price: 400, icon: 'fas fa-book-open text-blue-400', desc: 'A standard book for daily grammar practice.' },
    { id: 'edu_color_paper', category: 'edu', name: 'Color Paper', price: 500, icon: 'fas fa-copy text-pink-500', desc: 'Bright colorful papers for your art projects.' },
    { id: 'edu_notebook', category: 'edu', name: 'Notebook', price: 600, icon: 'fas fa-book text-indigo-500', desc: 'A premium notebook with thick pages.' },
    { id: 'edu_drawing_book', category: 'edu', name: 'Drawing Book', price: 700, icon: 'fas fa-book-reader text-orange-400', desc: 'A large book for your creative ideas.' },
    { id: 'edu_pencil_box', category: 'edu', name: 'Pencil Box', price: 1800, icon: 'fas fa-box text-purple-500', desc: 'A cool box to store all your stationery.' },
    { id: 'edu_adv_sharpener', category: 'edu', name: 'Advance Sharpener', price: 1850, icon: 'fas fa-cogs text-gray-700', desc: 'An automatic sharpener. Fast and easy!' },
    { id: 'edu_pencil_color', category: 'edu', name: 'Pencil Color', price: 1500, icon: 'fas fa-pencil-ruler text-yellow-600', desc: 'A set of 24 beautiful colored pencils.' },
    { id: 'edu_water_color', category: 'edu', name: 'Water Color', price: 2000, icon: 'fas fa-paint-brush text-teal-500', desc: 'Premium water colors for a masterpiece!' }
];

// ==========================================
// 3. DATA PENCAPAIAN (ACHIEVEMENTS)
// ==========================================
const ACHIEVEMENTS_LIST = [
    // --- Category 1: Leaderboard & Academics ---
    { id: "ach_01", name: "First Steps", description: "Collect 100 Total Score.", titleReward: "The Alphabet Apprentice", coinReward: 20 },
    { id: "ach_02", name: "Brainiac", description: "Collect 1,000 Total Score.", titleReward: "The Grammar Scholar", coinReward: 20 },
    { id: "ach_03", name: "Walking Dictionary", description: "Collect 5,000 Total Score.", titleReward: "The Vocabulary Virtuoso", coinReward: 20 },
    { id: "ach_04", name: "Einstein's Heir", description: "Collect 10,000 Total Score.", titleReward: "The Literary Mastermind", coinReward: 20 },
    { id: "ach_05", name: "Flawless English", description: "Get a Perfect Score in any 5 games.", titleReward: "The Perfect Proofreader", coinReward: 20 },

    // --- Category 2: Challenge Mode ---
    { id: "ach_06", name: "Brave Speaker", description: "Send your first challenge to a friend.", titleReward: "The Debate Challenger", coinReward: 20 },
    { id: "ach_07", name: "First Victory", description: "Win a friend's challenge for the first time.", titleReward: "The Fluent Victor", coinReward: 20 },
    { id: "ach_08", name: "Unbeatable", description: "Win 10 challenges overall.", titleReward: "The Spelling Champion", coinReward: 20 },
    { id: "ach_09", name: "Worthy Opponent", description: "Tie a friend's score in challenge mode.", titleReward: "The Peer Reviewer", coinReward: 20 },

    // --- Category 3: Economy & Wealth ---
    { id: "ach_10", name: "First Paycheck", description: "Collect 1,000 Coins.", titleReward: "The Knowledge Seeker", coinReward: 20 },
    { id: "ach_11", name: "Big Spender", description: "Spend 5,000 Coins in the Shop.", titleReward: "The Resource Investor", coinReward: 20 },
    { id: "ach_12", name: "Rolling in Gold", description: "Collect 20,000 Coins overall.", titleReward: "The Wealthy Wordsmith", coinReward: 20 },

    // --- Category 4: Avatar Collection ---
    { id: "ach_13", name: "New Look", description: "Buy your first avatar.", titleReward: "The Style Articulator", coinReward: 20 },
    { id: "ach_14", name: "Wardrobe Full", description: "Collect 5 different avatars.", titleReward: "The Guardian Collector", coinReward: 20 },
    { id: "ach_15", name: "Max Power", description: "Upgrade any avatar to Level 10 (Max Level).", titleReward: "The Syntax Sage", coinReward: 20 },
    { id: "ach_16", name: "Guardian Master", description: "Buy all animal or fantasy-themed avatars.", titleReward: "The Lore Keeper", coinReward: 20 },

    // --- Category 5: Dedication & Events ---
    { id: "ach_17", name: "Event Hunter", description: "Play during a Limited Time Event.", titleReward: "The Active Participant", coinReward: 20 },
    { id: "ach_18", name: "Night Owl", description: "Play a game after 10 PM.", titleReward: "The Midnight Reader", coinReward: 20 },
    { id: "ach_19", name: "Early Bird", description: "Play a game before 7 AM.", titleReward: "The Morning Orator", coinReward: 20 },

    // --- Category 6: Persistence & Streaks ---
    { id: "ach_20", name: "Weekend Warrior", description: "Play at least one game on a Saturday or Sunday.", titleReward: "The Weekend Writer", coinReward: 20 },
    { id: "ach_21", name: "3-Day Streak", description: "Play at least one game for 3 consecutive days.", titleReward: "The Consistent Student", coinReward: 20 },
    { id: "ach_22", name: "1-Week Streak", description: "Play for 7 consecutive days without failing.", titleReward: "The Dedicated Linguist", coinReward: 20 },
    { id: "ach_23", name: "Marathoner", description: "Complete 5 different games in a single day.", titleReward: "The Language Marathoner", coinReward: 20 },

    // --- Category 7: Game Mastery ---
    { id: "ach_24", name: "The Explorer", description: "Play all 12 games at least once.", titleReward: "The Syllabus Explorer", coinReward: 20 },
    { id: "ach_25", name: "Jack of All Trades", description: "Score at least 50 points in each of the 12 games.", titleReward: "The Polymath", coinReward: 20 },
    { id: "ach_26", name: "Comeback Kid", description: "Get a Perfect Score in a game you previously scored low in.", titleReward: "The Resilient Reviser", coinReward: 20 },
    { id: "ach_27", name: "Triple Threat", description: "Get a Perfect Score in 3 different games.", titleReward: "The English Prodigy", coinReward: 20 },

    // --- Category 8: Social & Advanced Challenges ---
    { id: "ach_28", name: "Friendly Rival", description: "Send 10 challenge codes to friends.", titleReward: "The Study Buddy", coinReward: 20 },
    { id: "ach_29", name: "Challenge Addict", description: "Complete 50 challenges overall.", titleReward: "The Forum Debater", coinReward: 20 },
    { id: "ach_30", name: "Good Sport", description: "Lose 5 challenges. Don't give up!", titleReward: "The Gracious Learner", coinReward: 20 },
    { id: "ach_31", name: "Close Call", description: "Win a challenge with a narrow margin of 1 to 5 points.", titleReward: "The Sharp Thinker", coinReward: 20 },
    { id: "ach_32", name: "Academic Comeback", description: "Defeat a friend who previously beat your record.", titleReward: "The Academic Redeemer", coinReward: 20 },

    // --- Category 9: Advanced Inventory ---
    { id: "ach_33", name: "Window Shopper", description: "Open the Shop menu 20 times.", titleReward: "The Curious Browser", coinReward: 20 },
    { id: "ach_34", name: "Avid Collector", description: "Collect 10 different avatars in your inventory.", titleReward: "The Archive Master", coinReward: 20 },
    { id: "ach_35", name: "Elite Squad", description: "Upgrade 3 different avatars to Level 10 (Max Level).", titleReward: "The Dean of Guardians", coinReward: 20 },
    { id: "ach_36", name: "Loyal Companion", description: "Equip the same avatar for 7 consecutive days.", titleReward: "The Steadfast Scholar", coinReward: 20 },

    // --- Category 10: Special Events & Hidden ---
    { id: "ach_37", name: "Merdeka Scholar", description: "Log in and play on August 31st.", titleReward: "The Patriotic Poet", coinReward: 20 },
    { id: "ach_38", name: "Holiday Gamer", description: "Log in and play during the December holidays.", titleReward: "The Festive Storyteller", coinReward: 20 },
    { id: "ach_39", name: "First Arrival", description: "Log in to the Game Hub for the first time.", titleReward: "The Freshman", coinReward: 20 },
    { id: "ach_40", name: "Secret Finder", description: "??? (Discover the hidden secret in the Game Hub)", titleReward: "The Context Detective", coinReward: 20 }
];
